apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-recreate-databases
spec:
  backoffLimit: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: recreate-databases
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
          command: [
              "sh",
              "-c",
              'mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD --execute "
              DROP DATABASE IF EXISTS enduro;
              CREATE DATABASE IF NOT EXISTS enduro;
              GRANT ALL PRIVILEGES ON enduro.* TO ''$MYSQL_USER''@''%'';
              DROP DATABASE IF EXISTS enduro_storage;
              CREATE DATABASE IF NOT EXISTS enduro_storage;
              GRANT ALL PRIVILEGES ON enduro_storage.* TO ''$MYSQL_USER''@''%'';
              DROP DATABASE IF EXISTS temporal;
              CREATE DATABASE IF NOT EXISTS temporal;
              GRANT ALL PRIVILEGES ON temporal.* TO ''$MYSQL_USER''@''%'';
              DROP DATABASE IF EXISTS temporal_visibility;
              CREATE DATABASE IF NOT EXISTS temporal_visibility;
              GRANT ALL PRIVILEGES ON temporal_visibility.* TO ''$MYSQL_USER''@''%'';
              "',
            ]
