{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hello World",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "content": "Howdy!" },
   "targets": [
    { "limit": 20, "tableType": "traces" }
   ]
  },
  { "title": "Traces and spans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total number of spans",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traces_spanmetrics_size_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing workflows",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "limit": 20,
     "query": "{name=\"StartWorkflow:processing-workflow\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "API requests",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "limit": 20,
     "query": "{name=\"api\"}",
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Service graph",
   "type": "nodeGraph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "limit": 20, "query": "{}", "tableType": "traces" }
   ]
  }
 ]
}