apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
spec:
  template:
    spec:
      containers:
        - name: opensearch
          env:
            - name: cluster.routing.allocation.disk.threshold_enabled
              value: "false"
