// Code generated by ent, DO NOT EDIT.

package db

import (
	"time"

	"github.com/artefactual-sdps/enduro/internal/persistence/ent/db/batch"
	"github.com/artefactual-sdps/enduro/internal/persistence/ent/db/sip"
	"github.com/artefactual-sdps/enduro/internal/persistence/ent/db/task"
	"github.com/artefactual-sdps/enduro/internal/persistence/ent/db/user"
	"github.com/artefactual-sdps/enduro/internal/persistence/ent/db/workflow"
	"github.com/artefactual-sdps/enduro/internal/persistence/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	batchFields := schema.Batch{}.Fields()
	_ = batchFields
	// batchDescSipsCount is the schema descriptor for sips_count field.
	batchDescSipsCount := batchFields[3].Descriptor()
	// batch.SipsCountValidator is a validator for the "sips_count" field. It is called by the builders before save.
	batch.SipsCountValidator = batchDescSipsCount.Validators[0].(func(int) error)
	// batchDescCreatedAt is the schema descriptor for created_at field.
	batchDescCreatedAt := batchFields[4].Descriptor()
	// batch.DefaultCreatedAt holds the default value on creation for the created_at field.
	batch.DefaultCreatedAt = batchDescCreatedAt.Default.(func() time.Time)
	// batchDescUploaderID is the schema descriptor for uploader_id field.
	batchDescUploaderID := batchFields[7].Descriptor()
	// batch.UploaderIDValidator is a validator for the "uploader_id" field. It is called by the builders before save.
	batch.UploaderIDValidator = batchDescUploaderID.Validators[0].(func(int) error)
	sipFields := schema.SIP{}.Fields()
	_ = sipFields
	// sipDescCreatedAt is the schema descriptor for created_at field.
	sipDescCreatedAt := sipFields[4].Descriptor()
	// sip.DefaultCreatedAt holds the default value on creation for the created_at field.
	sip.DefaultCreatedAt = sipDescCreatedAt.Default.(func() time.Time)
	// sipDescUploaderID is the schema descriptor for uploader_id field.
	sipDescUploaderID := sipFields[9].Descriptor()
	// sip.UploaderIDValidator is a validator for the "uploader_id" field. It is called by the builders before save.
	sip.UploaderIDValidator = sipDescUploaderID.Validators[0].(func(int) error)
	// sipDescBatchID is the schema descriptor for batch_id field.
	sipDescBatchID := sipFields[10].Descriptor()
	// sip.BatchIDValidator is a validator for the "batch_id" field. It is called by the builders before save.
	sip.BatchIDValidator = sipDescBatchID.Validators[0].(func(int) error)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescWorkflowID is the schema descriptor for workflow_id field.
	taskDescWorkflowID := taskFields[6].Descriptor()
	// task.WorkflowIDValidator is a validator for the "workflow_id" field. It is called by the builders before save.
	task.WorkflowIDValidator = taskDescWorkflowID.Validators[0].(func(int) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	workflowFields := schema.Workflow{}.Fields()
	_ = workflowFields
	// workflowDescSipID is the schema descriptor for sip_id field.
	workflowDescSipID := workflowFields[6].Descriptor()
	// workflow.SipIDValidator is a validator for the "sip_id" field. It is called by the builders before save.
	workflow.SipIDValidator = workflowDescSipID.Validators[0].(func(int) error)
}
