apiVersion: v1
kind: Secret
metadata:
  name: enduro-config-secret
type: Opaque
stringData:
  enduro.toml: |
    debug = false
    debugListen = "127.0.0.1:9001"

    [temporal]
    namespace = "default"
    address = "temporal:7233"
    taskqueue = "global"

    [api]
    listen = "0.0.0.0:9000"
    debug = false

    [database]
    dsn = "mysql_user:mysql_pass@tcp(mysql:3306)/enduro"

    [search]
    addresses = ["http://opensearch:9200"]
    username = "admin"
    password = "admin"

    [[watcher.minio]]
    name = "dev-minio"
    redisAddress = "redis://redis:6379"
    redisList = "minio-events"
    endpoint = "http://minio:9000"
    pathStyle = true
    key = "minio_user"
    secret = "minio_pass"
    region = "us-west-1"
    bucket = "sips"
    retentionPeriod = "10s"
    stripTopLevelDir = true

    [validation]
    checksumsCheckEnabled = false

    [storage]
    # internal processing bucket
    endpoint = "http://minio:9000"
    pathStyle = true
    key = "minio_user"
    secret = "minio_pass"
    region = "us-west-1"
    bucket = "aips"
    enduroAddress = "enduro:9000"

    [[storage.location]]
    name = "perma-aips-1"
    endpoint = "http://minio:9000"
    pathStyle = true
    key = "minio_user"
    secret = "minio_pass"
    region = "us-west-1"
    bucket = "perma-aips-1"

    [[storage.location]]
    name = "perma-aips-2"
    endpoint = "http://minio:9000"
    pathStyle = true
    key = "minio_user"
    secret = "minio_pass"
    region = "us-west-1"
    bucket = "perma-aips-2"

    [a3m]
    address = "127.0.0.1:7000"
    shareDir = "/home/a3m/.local/share/a3m/share"
