apiVersion: apps/v1
kind: Deployment
metadata:
  name: enduro
spec:
  template:
    spec:
      containers:
        - name: enduro
          volumeMounts:
            - name: config
              mountPath: /home/enduro/.config
      volumes:
        - name: config
          secret:
            secretName: enduro-config-secret
