# Validate this file:
#   curl --data-binary @codecov.yml https://codecov.io/validate

# Threshold should not be as high once all packages are being tracked.

comment:
  behavior: default

coverage:
  precision: 2
  round: down
  range: "25...75"
  status:
    project:
      default:
        threshold: 1.0%
    patch:
      default:
        threshold: 1.0%

ignore:
- "dashboard/"
- "docs/"
- "hack/"
- "internal/enums"
- "internal/**/fake/"
- "internal/**/gen/"
- "internal/**/ent/db/"
- "internal/**/ent/schema/"
