# Validate this file:
#   curl --data-binary @codecov.yml https://codecov.io/validate

# Threshold should not be as high once all packages are being tracked.

comment:
  behavior: default

coverage:
  precision: 2
  round: down
  range: "25...75"

ignore:
- "build"
- "hack"
- "dashboard"
- "fake"
- "gen"
