package workflow

import (
	"slices"
	"time"

	"github.com/artefactual-sdps/enduro/internal/enums"
	"github.com/artefactual-sdps/enduro/internal/ingest"
)

// workflowState is shared state that can be passed to activities.
type workflowState struct {
	// req is populated by the workflow request.
	req *ingest.ProcessingWorkflowRequest

	// status is the status of the workflow.
	status enums.WorkflowStatus

	// tempDirs is a list of temporary directories that should be deleted when
	// the workflow is complete.
	tempDirs []string

	// Identifier of the ingest workflow.
	//
	// It is populated by createWorkflowLocalActivity.
	workflowID int

	// sip, pip and aip track the state of the respective packages.
	sip *sipInfo
	pip *pipInfo
	aip *aipInfo

	// Send to failed information.
	sendToFailed sendToFailed
}

func newWorkflowState(req *ingest.ProcessingWorkflowRequest) *workflowState {
	return &workflowState{
		req:    req,
		status: enums.WorkflowStatusUnspecified,
		sip: &sipInfo{
			name:  req.Key,
			isDir: req.IsDir,

			// All SIPs start in queued status.
			status: enums.SIPStatusQueued,
		},

		// Initialize the PIP and AIP to empty structs to avoid nil pointer
		// dereference errors.
		pip: &pipInfo{},
		aip: &aipInfo{},
	}
}

// tempPath registers a filepath for deletion when a workflow session
// completes.
func (s *workflowState) tempPath(path string) {
	if path == "" || slices.Contains(s.tempDirs, path) {
		return
	}
	s.tempDirs = append(s.tempDirs, path)
}

// sipInfo is data about the SIP.
type sipInfo struct {
	// id is the UUID of the SIP.
	id string

	// name of the SIP.
	name string

	// status of the SIP.
	status enums.SIPStatus

	// isDir indicates whether the current working copy of the SIP is a
	// filesystem directory.
	isDir bool

	// sipType is the type of the SIP.
	sipType enums.SIPType

	// path is the temporary location of the working copy of the SIP.
	path string
}

// pipInfo represents the PIP, if one is created.
type pipInfo struct {
	// path is the path to the PIP. It is populated by
	// BundleActivity.
	path string
}

// aipInfo represents the AIP, if one is created.
type aipInfo struct {
	// id is the AIP UUID.
	//
	// It is populated when the preservation system creates the AIP.
	id string

	// path to the compressed AIP generated by a3m. It is left blank if AM
	// is used.
	//
	// It is populated once a3m creates the AIP.
	path string

	// storedAt is the time when the AIP is stored.
	storedAt time.Time
}

// sendToFailed tracks the SIP or PIP data required to send the package to
// the "failed" package location if processing fails.
type sendToFailed struct {
	// path of the SIP or PIP.
	path string

	// activityName is the name of the activity to send the package to the
	// correct failed bucket. The value can be "send-to-failed-sips" or
	// "send-to-failed-pips".
	activityName string

	// needsZipping indicates whether the package needs to be zipped before
	// uploading.
	needsZipping bool
}
