package entclient

import (
	"context"
	"time"

	"github.com/google/uuid"

	"github.com/artefactual-sdps/enduro/internal/datatypes"
	"github.com/artefactual-sdps/enduro/internal/persistence"
	"github.com/artefactual-sdps/enduro/internal/persistence/ent/db"
	"github.com/artefactual-sdps/enduro/internal/persistence/ent/db/pkg"
)

// CreatePackage creates and persists a new package using the values from pkg
// then returns the updated package.
//
// The input pkg "ID" and "CreatedAt" values are ignored; the stored package
// "ID" is generated by the persistence implementation and "CreatedAt" is always
// set to the current time.
func (c *client) CreatePackage(ctx context.Context, pkg *datatypes.Package) error {
	// Validate required fields.
	if pkg.Name == "" {
		return newRequiredFieldError("Name")
	}
	if pkg.WorkflowID == "" {
		return newRequiredFieldError("WorkflowID")
	}

	if pkg.RunID == "" {
		return newRequiredFieldError("RunID")
	}
	runID, err := uuid.Parse(pkg.RunID)
	if err != nil {
		return newParseError(err, "RunID")
	}

	q := c.ent.Pkg.Create().
		SetName(pkg.Name).
		SetWorkflowID(pkg.WorkflowID).
		SetRunID(runID).
		SetStatus(int8(pkg.Status)) // #nosec G115 -- constrained value.

	// Add optional fields.
	if pkg.AIPID.Valid {
		q.SetAipID(pkg.AIPID.UUID)
	}
	if pkg.LocationID.Valid {
		q.SetLocationID(pkg.LocationID.UUID)
	}
	if pkg.StartedAt.Valid {
		q.SetStartedAt(pkg.StartedAt.Time)
	}
	if pkg.CompletedAt.Valid {
		q.SetCompletedAt(pkg.CompletedAt.Time)
	}

	// Set CreatedAt to the current time
	q.SetCreatedAt(time.Now())

	// Save the package.
	p, err := q.Save(ctx)
	if err != nil {
		return newDBErrorWithDetails(err, "create package")
	}

	// Update pkg with DB data, to get generated values (e.g. ID).
	*pkg = *convertPkgToPackage(p)

	return nil
}

// UpdatePackage updates the persisted package identified by id using the
// updater function, then returns the updated package.
//
// The package "ID" and "CreatedAt" field values can not be updated with this
// method.
func (c *client) UpdatePackage(
	ctx context.Context,
	id int,
	updater persistence.PackageUpdater,
) (*datatypes.Package, error) {
	tx, err := c.ent.BeginTx(ctx, nil)
	if err != nil {
		return nil, newDBError(err)
	}

	p, err := tx.Pkg.Get(ctx, id)
	if err != nil {
		return nil, rollback(tx, newDBError(err))
	}

	up, err := updater(convertPkgToPackage(p))
	if err != nil {
		return nil, rollback(tx, newUpdaterError(err))
	}

	runID, err := uuid.Parse(up.RunID)
	if err != nil {
		return nil, rollback(tx, newParseError(err, "RunID"))
	}

	// Set required column values.
	q := tx.Pkg.UpdateOneID(id).
		SetName(up.Name).
		SetWorkflowID(up.WorkflowID).
		SetRunID(runID).
		SetStatus(int8(up.Status)) // #nosec G115 -- constrained value.

	// Set nullable column values.
	if up.AIPID.Valid {
		q.SetAipID(up.AIPID.UUID)
	}
	if up.LocationID.Valid {
		q.SetLocationID(up.LocationID.UUID)
	}
	if up.StartedAt.Valid {
		q.SetStartedAt(up.StartedAt.Time)
	}
	if up.CompletedAt.Valid {
		q.SetCompletedAt(up.CompletedAt.Time)
	}

	// Save changes.
	p, err = q.Save(ctx)
	if err != nil {
		return nil, rollback(tx, newDBError(err))
	}
	if err = tx.Commit(); err != nil {
		return nil, rollback(tx, newDBError(err))
	}

	return convertPkgToPackage(p), nil
}

// ListPackages returns a slice of packages filtered according to f.
func (c *client) ListPackages(ctx context.Context, f *persistence.PackageFilter) (
	[]*datatypes.Package, *persistence.Page, error,
) {
	res := []*datatypes.Package{}

	if f == nil {
		f = &persistence.PackageFilter{}
	}

	page, whole := filterPackages(c.ent.Pkg.Query(), f)

	r, err := page.All(ctx)
	if err != nil {
		return nil, nil, newDBError(err)
	}

	for _, i := range r {
		res = append(res, convertPkgToPackage(i))
	}

	total, err := whole.Count(ctx)
	if err != nil {
		return nil, nil, newDBError(err)
	}

	pp := &persistence.Page{
		Limit:  f.Limit,
		Offset: f.Offset,
		Total:  total,
	}

	return res, pp, err
}

// filterPackages applies the package filter f to the query q.
func filterPackages(q *db.PkgQuery, f *persistence.PackageFilter) (page, whole *db.PkgQuery) {
	qf := NewFilter(q, SortableFields{
		pkg.FieldID: {Name: "ID", Default: true},
	})
	qf.Equals(pkg.FieldName, f.Name)
	qf.Equals(pkg.FieldAipID, f.AIPID)
	qf.Equals(pkg.FieldLocationID, f.LocationID)
	qf.Equals(pkg.FieldStatus, f.Status)
	qf.AddDateRange(pkg.FieldCreatedAt, f.CreatedAt)
	qf.OrderBy(f.Sort)
	qf.Page(f.Limit, f.Offset)

	// Update the PackageFilter values with the actual values set on the query.
	// E.g. calling `h.Page(0,0)` will set the query limit equal to the default
	// page size.
	f.Limit = qf.limit
	f.Offset = qf.offset

	return qf.Apply()
}
