package entclient

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"

	"github.com/artefactual-sdps/enduro/internal/datatypes"
	"github.com/artefactual-sdps/enduro/internal/entfilter"
	"github.com/artefactual-sdps/enduro/internal/persistence"
	"github.com/artefactual-sdps/enduro/internal/persistence/ent/db"
	"github.com/artefactual-sdps/enduro/internal/persistence/ent/db/sip"
	"github.com/artefactual-sdps/enduro/internal/persistence/ent/db/user"
)

// CreateSIP creates and persists a new SIP using the values from s
// then returns the updated SIP.
//
// The input SIP "ID" and "CreatedAt" values are ignored; the stored SIP
// "ID" is generated by the persistence implementation and "CreatedAt" is always
// set to the current time.
func (c *client) CreateSIP(ctx context.Context, s *datatypes.SIP) error {
	// Validate required fields.
	if s.UUID == uuid.Nil {
		return newRequiredFieldError("UUID")
	}
	if s.Name == "" {
		return newRequiredFieldError("Name")
	}

	q := c.ent.SIP.Create().
		SetUUID(s.UUID).
		SetName(s.Name).
		SetStatus(s.Status)

	// Add optional fields.
	if s.AIPID.Valid {
		q.SetAipID(s.AIPID.UUID)
	}
	if s.StartedAt.Valid {
		q.SetStartedAt(s.StartedAt.Time)
	}
	if s.CompletedAt.Valid {
		q.SetCompletedAt(s.CompletedAt.Time)
	}

	var uploaderUUID *uuid.UUID
	if s.UploaderID != nil {
		u, err := c.ent.User.Query().Where(user.UUID(*s.UploaderID)).Only(ctx)
		if err != nil {
			return newDBError(errors.New("create SIP: uploader not found"))
		}
		q.SetUser(u)
		uploaderUUID = &u.UUID
	}

	// Set CreatedAt to the current time
	q.SetCreatedAt(time.Now())

	// Save the SIP.
	dbs, err := q.Save(ctx)
	if err != nil {
		return newDBErrorWithDetails(err, "create SIP")
	}

	// Update SIP with DB data, to get generated values (e.g. ID).
	*s = *convertSIP(dbs)

	// Manually set the UploaderID because the dbs result doesn't include the
	// user edge, so we can't directly get the user UUID from it.
	if uploaderUUID != nil {
		s.UploaderID = uploaderUUID
	}

	return nil
}

// UpdateSIP updates the persisted SIP identified by id using the
// updater function, then returns the updated SIP.
//
// The SIP "ID" and "CreatedAt" field values can not be updated with this
// method.
func (c *client) UpdateSIP(
	ctx context.Context,
	id uuid.UUID,
	updater persistence.SIPUpdater,
) (*datatypes.SIP, error) {
	tx, err := c.ent.BeginTx(ctx, nil)
	if err != nil {
		return nil, newDBError(err)
	}

	// Get the current SIP data from the database.
	dbs, err := tx.SIP.Query().Where(sip.UUID(id)).Only(ctx)
	if err != nil {
		return nil, rollback(tx, newDBError(err))
	}

	// Keep database ID in case it's changed by the updater.
	dbID := dbs.ID

	// Get an updated datatypes.SIP from the updater function.
	up, err := updater(convertSIP(dbs))
	if err != nil {
		return nil, rollback(tx, newUpdaterError(err))
	}

	// Save the updated SIP data to the database.
	q := tx.SIP.UpdateOneID(dbID).SetName(up.Name)

	// Validate columns.
	if up.Status.IsValid() {
		q.SetStatus(up.Status)
	}

	// Set optional column values.
	if up.AIPID.Valid {
		q.SetAipID(up.AIPID.UUID)
	}
	if up.StartedAt.Valid {
		q.SetStartedAt(up.StartedAt.Time)
	}
	if up.CompletedAt.Valid {
		q.SetCompletedAt(up.CompletedAt.Time)
	}
	if up.FailedAs.IsValid() {
		q.SetFailedAs(up.FailedAs)
	}
	if up.FailedKey != "" {
		q.SetFailedKey(up.FailedKey)
	}

	// If the UploaderID is set, find the user and set it on the query.
	var userUUID *uuid.UUID
	if up.UploaderID != nil {
		u, err := c.ent.User.Query().Where(user.UUID(*up.UploaderID)).Only(ctx)
		if err != nil {
			return nil, rollback(tx, newDBError(errors.New("update SIP: uploader not found")))
		}
		q.SetUser(u)
		userUUID = &u.UUID
	}

	// Save changes.
	dbs, err = q.Save(ctx)
	if err != nil {
		return nil, rollback(tx, newDBError(err))
	}
	if err = tx.Commit(); err != nil {
		return nil, rollback(tx, newDBError(err))
	}

	s := convertSIP(dbs)

	// Manually set the UploaderID because the dbs result doesn't include the
	// user edge, so we can't directly get the user UUID from it.
	if userUUID != nil {
		s.UploaderID = userUUID
	}

	return s, nil
}

// DeleteSIP deletes the persisted SIP identified by id.
func (c *client) DeleteSIP(ctx context.Context, id int) error {
	if err := c.ent.SIP.DeleteOneID(id).Exec(ctx); err != nil {
		return newDBErrorWithDetails(err, "delete SIP")
	}

	return nil
}

// ReadSIP returns the SIP identified by id.
func (c *client) ReadSIP(ctx context.Context, id uuid.UUID) (*datatypes.SIP, error) {
	s, err := c.ent.SIP.Query().Where(sip.UUID(id)).WithUser().Only(ctx)
	if err != nil {
		return nil, newDBError(err)
	}

	return convertSIP(s), nil
}

// ListSIPs returns a slice of SIPs filtered according to f.
func (c *client) ListSIPs(ctx context.Context, f *persistence.SIPFilter) (
	[]*datatypes.SIP, *persistence.Page, error,
) {
	res := []*datatypes.SIP{}

	if f == nil {
		f = &persistence.SIPFilter{}
	}

	page, whole := filterSIPs(c.ent.SIP.Query().WithUser(), f)

	r, err := page.All(ctx)
	if err != nil {
		return nil, nil, newDBError(err)
	}

	for _, i := range r {
		res = append(res, convertSIP(i))
	}

	total, err := whole.Count(ctx)
	if err != nil {
		return nil, nil, newDBError(err)
	}

	pp := &persistence.Page{
		Limit:  f.Limit,
		Offset: f.Offset,
		Total:  total,
	}

	return res, pp, err
}

// filterSIPs applies the SIP filter f to the query q.
func filterSIPs(q *db.SIPQuery, f *persistence.SIPFilter) (page, whole *db.SIPQuery) {
	qf := entfilter.NewFilter(q, entfilter.SortableFields{
		sip.FieldID: {Name: "ID", Default: true},
	})
	qf.Contains(sip.FieldName, f.Name)
	qf.Equals(sip.FieldAipID, f.AIPID)
	qf.Equals(sip.FieldStatus, f.Status)
	qf.AddDateRange(sip.FieldCreatedAt, f.CreatedAt)
	qf.OrderBy(f.Sort)
	qf.Page(f.Limit, f.Offset)

	// Update the SIPFilter values with the actual values set on the query.
	// E.g. calling `qf.Page(0,0)` will set the query limit equal to the default
	// page size.
	f.Limit = qf.Limit
	f.Offset = qf.Offset

	return qf.Apply()
}
