apiVersion: apps/v1
kind: Deployment
metadata:
  name: enduro
  labels:
    app: enduro
spec:
  selector:
    matchLabels:
      app: enduro
  template:
    metadata:
      labels:
        app: enduro
    spec:
      serviceAccountName: sdps
      initContainers:
        - name: check-temporal
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              "until echo STATUS | nc -w 2 temporal.enduro-sdps 7233; do echo waiting for temporal to start; sleep 1; done;",
            ]
      containers:
        - name: enduro
          image: ghcr.io/artefactual-sdps/enduro:main
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: user
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: password
            - name: ENDURO_DATABASE_DSN
              value: $(MYSQL_USER):$(MYSQL_PASSWORD)@tcp(mysql.enduro-sdps:3306)/enduro
            - name: ENDURO_STORAGE_DATABASE_DSN
              value: $(MYSQL_USER):$(MYSQL_PASSWORD)@tcp(mysql.enduro-sdps:3306)/enduro_storage
            - name: ENDURO_WATCHER_EMBEDDED_KEY
              value: "$(MINIO_USER)"
            - name: ENDURO_WATCHER_EMBEDDED_SECRET
              value: "$(MINIO_PASSWORD)"
            - name: ENDURO_STORAGE_INTERNAL_KEY
              value: $(MINIO_USER)
            - name: ENDURO_STORAGE_INTERNAL_SECRET
              value: $(MINIO_PASSWORD)
            - name: ENDURO_UPLOAD_KEY
              value: $(MINIO_USER)
            - name: ENDURO_UPLOAD_SECRET
              value: $(MINIO_PASSWORD)
            - name: ENDURO_TELEMETRY_TRACES_ENABLED
              value: "true"
            - name: ENDURO_TELEMETRY_TRACES_ADDRESS
              value: "grafana-alloy.enduro-sdps:4317"
            - name: ENDURO_TELEMETRY_TRACES_SAMPLING_RATIO
              value: "1.0"
            - name: ENDURO_VALIDATEPREMIS_ENABLED
              value: "false"
          ports:
            - containerPort: 9000
            - containerPort: 9002
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: enduro
  labels:
    app: enduro
spec:
  selector:
    app: enduro
  ports:
    - name: api
      port: 9000
    - name: internalapi
      port: 9002
