apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enduro-a3m
  labels:
    app: enduro-a3m
spec:
  serviceName: enduro-a3m
  selector:
    matchLabels:
      app: enduro-a3m
  template:
    metadata:
      labels:
        app: enduro-a3m
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: check-temporal
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              "until echo STATUS | nc -w 2 temporal.sdps 7233; do echo waiting for temporal to start; sleep 1; done;",
            ]
      containers:
        - name: enduro-a3m-worker
          image: ghcr.io/artefactual-sdps/enduro-a3m-worker:main
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: user
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: password
            - name: ENDURO_DATABASE_DSN
              value: $(MYSQL_USER):$(MYSQL_PASSWORD)@tcp(mysql.sdps:3306)/enduro
            - name: ENDURO_STORAGE_DATABASE_DSN
              value: $(MYSQL_USER):$(MYSQL_PASSWORD)@tcp(mysql.sdps:3306)/enduro_storage
            - name: ENDURO_WATCHER_EMBEDDED_KEY
              value: $(MINIO_USER)
            - name: ENDURO_WATCHER_EMBEDDED_SECRET
              value: $(MINIO_PASSWORD)
            - name: ENDURO_STORAGE_INTERNAL_KEY
              value: $(MINIO_USER)
            - name: ENDURO_STORAGE_INTERNAL_SECRET
              value: $(MINIO_PASSWORD)
            - name: ENDURO_UPLOAD_KEY
              value: $(MINIO_USER)
            - name: ENDURO_UPLOAD_SECRET
              value: $(MINIO_PASSWORD)
          volumeMounts:
            - name: enduro-a3m
              mountPath: /home/a3m/.local/share/a3m/share
        - name: a3m
          image: ghcr.io/artefactual-labs/a3m:main
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          volumeMounts:
            - name: enduro-a3m
              mountPath: /home/a3m/.local/share/a3m/share
  volumeClaimTemplates:
    - metadata:
        name: enduro-a3m
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
