apiVersion: apps/v1
kind: Deployment
metadata:
  name: enduro-internal
  labels:
    app: enduro-internal
spec:
  selector:
    matchLabels:
      app: enduro-internal
  template:
    metadata:
      labels:
        app: enduro-internal
    spec:
      initContainers:
        - name: check-temporal
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              "until echo STATUS | nc -w 2 temporal.enduro 7233; do echo waiting for temporal to start; sleep 1; done;",
            ]
      containers:
        - name: enduro-internal
          image: ghcr.io/artefactual-sdps/enduro:main
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: user
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: password
            - name: ENDURO_DATABASE_DSN
              value: $(MYSQL_USER):$(MYSQL_PASSWORD)@tcp(mysql.enduro:3306)/enduro
            - name: ENDURO_STORAGE_DATABASE_DSN
              value: $(MYSQL_USER):$(MYSQL_PASSWORD)@tcp(mysql.enduro:3306)/enduro_storage
            - name: ENDURO_WATCHER_EMBEDDED_KEY
              value: "$(MINIO_USER)"
            - name: ENDURO_WATCHER_EMBEDDED_SECRET
              value: "$(MINIO_PASSWORD)"
            - name: ENDURO_STORAGE_INTERNAL_KEY
              value: $(MINIO_USER)
            - name: ENDURO_STORAGE_INTERNAL_SECRET
              value: $(MINIO_PASSWORD)
            - name: ENDURO_UPLOAD_KEY
              value: $(MINIO_USER)
            - name: ENDURO_UPLOAD_SECRET
              value: $(MINIO_PASSWORD)
            - name: ENDURO_API_AUTH_ENABLED
              value: "false"
          ports:
            - containerPort: 9000
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: enduro-internal
  labels:
    app: enduro-internal
spec:
  selector:
    app: enduro-internal
  ports:
    - port: 9000
