apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup-buckets
spec:
  backoffLimit: 100
  template:
    spec:
      serviceAccountName: sdps
      restartPolicy: OnFailure
      containers:
        - name: setup-buckets
          image: minio/mc
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: user
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: password
          command: [
              "sh",
              "-c",
              "mc alias set enduro http://minio.enduro-sdps:9000 ${MINIO_USER} ${MINIO_PASSWORD};
              mc mb enduro/sips --ignore-existing;
              mc mb enduro/aips --ignore-existing;
              mc mb enduro/perma-aips-1 --ignore-existing;
              mc mb enduro/perma-aips-2 --ignore-existing;
              mc mb enduro/failed-sips --ignore-existing;
              mc mb enduro/failed-pips --ignore-existing;
              mc event add enduro/sips arn:minio:sqs::PRIMARY:redis --event put --ignore-existing;
              mc admin policy rm enduro deny-dir-uploads;
              mc admin policy create enduro deny-dir-uploads /root/.mc/policies/deny-dir-uploads.json;
              mc admin policy rm enduro sips-zip-only;
              mc admin policy create enduro sips-zip-only /root/.mc/policies/sips-zip-only.json;",
            ]
          volumeMounts:
            - name: config
              mountPath: /root/.mc/policies
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: minio-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-configmap
data:
  deny-dir-uploads.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Deny",
          "Action": "s3:PutObject",
          "Resource": "arn:aws:s3:::*/*/*"
        }
      ]
    }
  sips-zip-only.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": "s3:PutObject",
          "Resource": "arn:aws:s3:::sips/*.zip"
        }
      ]
    }
