apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup-buckets
spec:
  backoffLimit: 100
  template:
    spec:
      restartPolicy: "OnFailure"
      initContainers:
        - name: check-minio
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              "until echo STATUS | nc -w 2 minio 9000; do echo waiting for minio to start; sleep 1; done;",
            ]
      containers:
        - name: setup-buckets
          image: "minio/mc"
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: user
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: password
          command: [
              "sh",
              "-c",
              "mc alias set enduro http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD}; \
              mc mb enduro/sips --ignore-existing; \
              mc mb enduro/aips --ignore-existing; \
              mc mb enduro/perma-aips-1 --ignore-existing; \
              mc mb enduro/perma-aips-2 --ignore-existing; \
              mc event add enduro/sips arn:minio:sqs::PRIMARY:redis --event put --ignore-existing",
            ]
