apiVersion: v1
data:
  readwrite_sip_zips.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": ["s3:*"],
          "Resource": ["arn:aws:s3:::sips/*.zip"]
        }
      ]
    }
kind: ConfigMap
metadata:
  name: zips-policy-configmap
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup-buckets
spec:
  backoffLimit: 100
  template:
    spec:
      serviceAccountName: sdps
      restartPolicy: OnFailure
      containers:
        - name: setup-buckets
          image: minio/mc
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: user
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: password
          volumeMounts:
            - name: zips-policy-config-volume
              mountPath: /etc/config
          command: [
              "sh",
              "-c",
              "mc alias set enduro http://minio.enduro-sdps:9000 ${MINIO_USER} ${MINIO_PASSWORD};
              mc mb enduro/sips --ignore-existing;
              mc mb enduro/failed-transfers --ignore-existing;
              mc mb enduro/failed-sips --ignore-existing;
              mc mb enduro/aips --ignore-existing;
              mc mb enduro/perma-aips-1 --ignore-existing;
              mc mb enduro/perma-aips-2 --ignore-existing;
              mc event add enduro/sips arn:minio:sqs::PRIMARY:redis --event put --ignore-existing;
              mc admin policy create enduro readwritesips /etc/config/readwrite_sip_zips.json",
            ]
      volumes:
        - name: zips-policy-config-volume
          configMap:
            name: zips-policy-configmap
