apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-create-locations
spec:
  backoffLimit: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-locations
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: user
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: password
          command:
            - sh
            - -c
            - >
              KEY=$(echo $MINIO_USER | iconv -t utf-8) && 
              SECRET=$(echo $MINIO_PASSWORD | iconv -t utf-8) &&
              LOC_1='{"s3": {"bucket": "perma-aips-1", "region": "us-west-1", "endpoint": "http://minio.enduro:9000", "path_style": true, "key": "'$KEY'", "secret": "'$SECRET'"}}' &&
              LOC_2='{"s3": {"bucket": "perma-aips-2", "region": "us-west-1", "endpoint": "http://minio.enduro:9000", "path_style": true, "key": "'$KEY'", "secret": "'$SECRET'"}}' &&
              mysql -h mysql.enduro -u $MYSQL_USER -p$MYSQL_PASSWORD --execute "
                INSERT IGNORE INTO enduro_storage.location (name, description, source, purpose, uuid, created_at, config)
                VALUES ('perma-aips-1', '', 'minio', 'aip_store', 'f2cc963f-c14d-4eaa-b950-bd207189a1f1', NOW(), '$LOC_1');
                INSERT IGNORE INTO enduro_storage.location (name, description, source, purpose, uuid, created_at, config)
                VALUES ('perma-aips-2', '', 'minio', 'aip_store', '0a7cc888-67ea-445c-8a64-6f8dfcf373e5', NOW(), '$LOC_2');
              " && echo "Locations created"
