apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      serviceAccountName: sdps
      containers:
        - name: redis
          image: redis:7
          command: ["sh", "-c", "redis-server --appendonly yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources: {}
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-persistentvolumeclaim
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-persistentvolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
