apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  labels:
    app: temporal-ui
spec:
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: temporalio/ui:2.16.1
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal.enduro:7233
            - name: TEMPORAL_UI_PORT
              value: "8080"
            - name: TEMPORAL_CORS_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: temporal-ui-secret
                  key: cors-origins
            - name: TEMPORAL_AUTH_ENABLED
              value: "true"
            - name: TEMPORAL_AUTH_PROVIDER_URL
              valueFrom:
                secretKeyRef:
                  name: temporal-ui-secret
                  key: auth-provider-url
            - name: TEMPORAL_AUTH_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: temporal-ui-secret
                  key: auth-callback-url
            - name: TEMPORAL_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: temporal-ui-secret
                  key: auth-client-id
            - name: TEMPORAL_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: temporal-ui-secret
                  key: auth-client-secret
          ports:
            - containerPort: 8080
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  labels:
    app: temporal-ui
spec:
  selector:
    app: temporal-ui
  ports:
    - port: 8080
