apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enduro-sdps
resources:
  - ../dev-am
  - ../../components/seaweedfs
patches:
  - path: enduro-seaweedfs-patch.yaml
    target:
      kind: Deployment
      name: enduro
  - path: enduro-am-seaweedfs-patch.yaml
    target:
      kind: Deployment
      name: enduro-am
