/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddBatchRequestBody,
  AddSipResponseBody,
  BatchNotFound,
  ConfirmSipRequestBody,
  EnduroIngestBatch,
  EnduroIngestBatches,
  EnduroIngestSip,
  EnduroIngestSipDecision,
  EnduroIngestSipWorkflows,
  EnduroIngestSips,
  EnduroIngestSipsourceObjects,
  EnduroIngestUsers,
  IngestEvent,
  ReviewBatchRequestBody,
  SIPNotFound,
  SubmitSipDecisionRequestBody,
} from '../models/index';
import {
    AddBatchRequestBodyFromJSON,
    AddBatchRequestBodyToJSON,
    AddSipResponseBodyFromJSON,
    AddSipResponseBodyToJSON,
    BatchNotFoundFromJSON,
    BatchNotFoundToJSON,
    ConfirmSipRequestBodyFromJSON,
    ConfirmSipRequestBodyToJSON,
    EnduroIngestBatchFromJSON,
    EnduroIngestBatchToJSON,
    EnduroIngestBatchesFromJSON,
    EnduroIngestBatchesToJSON,
    EnduroIngestSipFromJSON,
    EnduroIngestSipToJSON,
    EnduroIngestSipDecisionFromJSON,
    EnduroIngestSipDecisionToJSON,
    EnduroIngestSipWorkflowsFromJSON,
    EnduroIngestSipWorkflowsToJSON,
    EnduroIngestSipsFromJSON,
    EnduroIngestSipsToJSON,
    EnduroIngestSipsourceObjectsFromJSON,
    EnduroIngestSipsourceObjectsToJSON,
    EnduroIngestUsersFromJSON,
    EnduroIngestUsersToJSON,
    IngestEventFromJSON,
    IngestEventToJSON,
    ReviewBatchRequestBodyFromJSON,
    ReviewBatchRequestBodyToJSON,
    SIPNotFoundFromJSON,
    SIPNotFoundToJSON,
    SubmitSipDecisionRequestBodyFromJSON,
    SubmitSipDecisionRequestBodyToJSON,
} from '../models/index';

export interface IngestAddBatchRequest {
    addBatchRequestBody: AddBatchRequestBody;
}

export interface IngestAddSipRequest {
    sourceId: string;
    key: string;
}

export interface IngestConfirmSipRequest {
    uuid: string;
    confirmSipRequestBody: ConfirmSipRequestBody;
}

export interface IngestDownloadSipRequest {
    uuid: string;
    enduroSipDownloadTicket?: string;
}

export interface IngestDownloadSipRequestRequest {
    uuid: string;
}

export interface IngestListBatchesRequest {
    identifier?: string;
    earliestCreatedTime?: Date;
    latestCreatedTime?: Date;
    status?: IngestListBatchesStatusEnum;
    uploaderUuid?: string;
    limit?: number;
    offset?: number;
}

export interface IngestListSipSourceObjectsRequest {
    uuid: string;
    limit?: number;
    cursor?: string;
}

export interface IngestListSipWorkflowsRequest {
    uuid: string;
}

export interface IngestListSipsRequest {
    name?: string;
    aipUuid?: string;
    earliestCreatedTime?: Date;
    latestCreatedTime?: Date;
    status?: IngestListSipsStatusEnum;
    uploaderUuid?: string;
    batchUuid?: string;
    limit?: number;
    offset?: number;
}

export interface IngestListUsersRequest {
    email?: string;
    name?: string;
    limit?: number;
    offset?: number;
}

export interface IngestMonitorRequest {
    enduroIngestWsTicket?: string;
}

export interface IngestRejectSipRequest {
    uuid: string;
}

export interface IngestReviewBatchRequest {
    uuid: string;
    reviewBatchRequestBody: ReviewBatchRequestBody;
}

export interface IngestShowBatchRequest {
    uuid: string;
}

export interface IngestShowSipRequest {
    uuid: string;
}

export interface IngestShowSipDecisionRequest {
    uuid: string;
}

export interface IngestSubmitSipDecisionRequest {
    uuid: string;
    submitSipDecisionRequestBody: SubmitSipDecisionRequestBody;
}

export interface IngestUploadSipRequest {
    contentType?: string;
}

/**
 * IngestApi - interface
 * 
 * @export
 * @interface IngestApiInterface
 */
export interface IngestApiInterface {
    /**
     * Creates request options for ingestAddBatch without sending the request
     * @param {AddBatchRequestBody} addBatchRequestBody 
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestAddBatchRequestOpts(requestParameters: IngestAddBatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Ingest a Batch from a SIP Source
     * @summary add_batch ingest
     * @param {AddBatchRequestBody} addBatchRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestAddBatchRaw(requestParameters: IngestAddBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddSipResponseBody>>;

    /**
     * Ingest a Batch from a SIP Source
     * add_batch ingest
     */
    ingestAddBatch(requestParameters: IngestAddBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddSipResponseBody>;

    /**
     * Creates request options for ingestAddSip without sending the request
     * @param {string} sourceId Identifier of SIP source -- CURRENTLY NOT USED
     * @param {string} key Key of the item to ingest
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestAddSipRequestOpts(requestParameters: IngestAddSipRequest): Promise<runtime.RequestOpts>;

    /**
     * Ingest a SIP from a SIP Source
     * @summary add_sip ingest
     * @param {string} sourceId Identifier of SIP source -- CURRENTLY NOT USED
     * @param {string} key Key of the item to ingest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestAddSipRaw(requestParameters: IngestAddSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddSipResponseBody>>;

    /**
     * Ingest a SIP from a SIP Source
     * add_sip ingest
     */
    ingestAddSip(requestParameters: IngestAddSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddSipResponseBody>;

    /**
     * Creates request options for ingestConfirmSip without sending the request
     * @param {string} uuid Identifier of SIP to look up
     * @param {ConfirmSipRequestBody} confirmSipRequestBody 
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestConfirmSipRequestOpts(requestParameters: IngestConfirmSipRequest): Promise<runtime.RequestOpts>;

    /**
     * Signal the SIP has been reviewed and accepted
     * @summary confirm_sip ingest
     * @param {string} uuid Identifier of SIP to look up
     * @param {ConfirmSipRequestBody} confirmSipRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestConfirmSipRaw(requestParameters: IngestConfirmSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Signal the SIP has been reviewed and accepted
     * confirm_sip ingest
     */
    ingestConfirmSip(requestParameters: IngestConfirmSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for ingestDownloadSip without sending the request
     * @param {string} uuid Identifier of the SIP to download
     * @param {string} [enduroSipDownloadTicket] 
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestDownloadSipRequestOpts(requestParameters: IngestDownloadSipRequest): Promise<runtime.RequestOpts>;

    /**
     * Download the failed package related to a SIP. It will be the original SIP or the transformed PIP, based on the SIP\'s `failed_as` value.
     * @summary download_sip ingest
     * @param {string} uuid Identifier of the SIP to download
     * @param {string} [enduroSipDownloadTicket] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestDownloadSipRaw(requestParameters: IngestDownloadSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     * Download the failed package related to a SIP. It will be the original SIP or the transformed PIP, based on the SIP\'s `failed_as` value.
     * download_sip ingest
     */
    ingestDownloadSip(requestParameters: IngestDownloadSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * Creates request options for ingestDownloadSipRequest without sending the request
     * @param {string} uuid Identifier of the SIP to download
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestDownloadSipRequestRequestOpts(requestParameters: IngestDownloadSipRequestRequest): Promise<runtime.RequestOpts>;

    /**
     * Request access to SIP download
     * @summary download_sip_request ingest
     * @param {string} uuid Identifier of the SIP to download
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestDownloadSipRequestRaw(requestParameters: IngestDownloadSipRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Request access to SIP download
     * download_sip_request ingest
     */
    ingestDownloadSipRequest(requestParameters: IngestDownloadSipRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for ingestListBatches without sending the request
     * @param {string} [identifier] 
     * @param {Date} [earliestCreatedTime] 
     * @param {Date} [latestCreatedTime] 
     * @param {'queued' | 'processing' | 'pending' | 'ingested' | 'canceled' | 'failed'} [status] 
     * @param {string} [uploaderUuid] UUID of the Batch uploader
     * @param {number} [limit] Limit number of results to return
     * @param {number} [offset] Offset from the beginning of the found set
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestListBatchesRequestOpts(requestParameters: IngestListBatchesRequest): Promise<runtime.RequestOpts>;

    /**
     * List all ingested Batches
     * @summary list_batches ingest
     * @param {string} [identifier] 
     * @param {Date} [earliestCreatedTime] 
     * @param {Date} [latestCreatedTime] 
     * @param {'queued' | 'processing' | 'pending' | 'ingested' | 'canceled' | 'failed'} [status] 
     * @param {string} [uploaderUuid] UUID of the Batch uploader
     * @param {number} [limit] Limit number of results to return
     * @param {number} [offset] Offset from the beginning of the found set
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestListBatchesRaw(requestParameters: IngestListBatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestBatches>>;

    /**
     * List all ingested Batches
     * list_batches ingest
     */
    ingestListBatches(requestParameters: IngestListBatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestBatches>;

    /**
     * Creates request options for ingestListSipSourceObjects without sending the request
     * @param {string} uuid SIP source identifier -- CURRENTLY NOT USED
     * @param {number} [limit] Limit the number of results to return
     * @param {string} [cursor] Cursor token to get subsequent pages
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestListSipSourceObjectsRequestOpts(requestParameters: IngestListSipSourceObjectsRequest): Promise<runtime.RequestOpts>;

    /**
     * List the objects in a SIP source
     * @summary list_sip_source_objects ingest
     * @param {string} uuid SIP source identifier -- CURRENTLY NOT USED
     * @param {number} [limit] Limit the number of results to return
     * @param {string} [cursor] Cursor token to get subsequent pages
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestListSipSourceObjectsRaw(requestParameters: IngestListSipSourceObjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestSipsourceObjects>>;

    /**
     * List the objects in a SIP source
     * list_sip_source_objects ingest
     */
    ingestListSipSourceObjects(requestParameters: IngestListSipSourceObjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestSipsourceObjects>;

    /**
     * Creates request options for ingestListSipWorkflows without sending the request
     * @param {string} uuid Identifier of SIP to look up
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestListSipWorkflowsRequestOpts(requestParameters: IngestListSipWorkflowsRequest): Promise<runtime.RequestOpts>;

    /**
     * List all workflows for a SIP
     * @summary list_sip_workflows ingest
     * @param {string} uuid Identifier of SIP to look up
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestListSipWorkflowsRaw(requestParameters: IngestListSipWorkflowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestSipWorkflows>>;

    /**
     * List all workflows for a SIP
     * list_sip_workflows ingest
     */
    ingestListSipWorkflows(requestParameters: IngestListSipWorkflowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestSipWorkflows>;

    /**
     * Creates request options for ingestListSips without sending the request
     * @param {string} [name] 
     * @param {string} [aipUuid] Identifier of AIP
     * @param {Date} [earliestCreatedTime] 
     * @param {Date} [latestCreatedTime] 
     * @param {'error' | 'failed' | 'queued' | 'processing' | 'pending' | 'ingested' | 'validated' | 'canceled'} [status] 
     * @param {string} [uploaderUuid] UUID of the SIP uploader
     * @param {string} [batchUuid] UUID of the related Batch
     * @param {number} [limit] Limit number of results to return
     * @param {number} [offset] Offset from the beginning of the found set
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestListSipsRequestOpts(requestParameters: IngestListSipsRequest): Promise<runtime.RequestOpts>;

    /**
     * List all ingested SIPs
     * @summary list_sips ingest
     * @param {string} [name] 
     * @param {string} [aipUuid] Identifier of AIP
     * @param {Date} [earliestCreatedTime] 
     * @param {Date} [latestCreatedTime] 
     * @param {'error' | 'failed' | 'queued' | 'processing' | 'pending' | 'ingested' | 'validated' | 'canceled'} [status] 
     * @param {string} [uploaderUuid] UUID of the SIP uploader
     * @param {string} [batchUuid] UUID of the related Batch
     * @param {number} [limit] Limit number of results to return
     * @param {number} [offset] Offset from the beginning of the found set
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestListSipsRaw(requestParameters: IngestListSipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestSips>>;

    /**
     * List all ingested SIPs
     * list_sips ingest
     */
    ingestListSips(requestParameters: IngestListSipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestSips>;

    /**
     * Creates request options for ingestListUsers without sending the request
     * @param {string} [email] Email of the user
     * @param {string} [name] Name of the user
     * @param {number} [limit] Limit number of results to return
     * @param {number} [offset] Offset from the beginning of the found set
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestListUsersRequestOpts(requestParameters: IngestListUsersRequest): Promise<runtime.RequestOpts>;

    /**
     * List all users
     * @summary list_users ingest
     * @param {string} [email] Email of the user
     * @param {string} [name] Name of the user
     * @param {number} [limit] Limit number of results to return
     * @param {number} [offset] Offset from the beginning of the found set
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestListUsersRaw(requestParameters: IngestListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestUsers>>;

    /**
     * List all users
     * list_users ingest
     */
    ingestListUsers(requestParameters: IngestListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestUsers>;

    /**
     * Creates request options for ingestMonitor without sending the request
     * @param {string} [enduroIngestWsTicket] 
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestMonitorRequestOpts(requestParameters: IngestMonitorRequest): Promise<runtime.RequestOpts>;

    /**
     * Obtain access to the /monitor WebSocket
     * @summary monitor ingest
     * @param {string} [enduroIngestWsTicket] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestMonitorRaw(requestParameters: IngestMonitorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Obtain access to the /monitor WebSocket
     * monitor ingest
     */
    ingestMonitor(requestParameters: IngestMonitorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for ingestMonitorRequest without sending the request
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestMonitorRequestRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Request access to the /monitor WebSocket
     * @summary monitor_request ingest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestMonitorRequestRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Request access to the /monitor WebSocket
     * monitor_request ingest
     */
    ingestMonitorRequest(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for ingestRejectSip without sending the request
     * @param {string} uuid Identifier of SIP to look up
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestRejectSipRequestOpts(requestParameters: IngestRejectSipRequest): Promise<runtime.RequestOpts>;

    /**
     * Signal the SIP has been reviewed and rejected
     * @summary reject_sip ingest
     * @param {string} uuid Identifier of SIP to look up
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestRejectSipRaw(requestParameters: IngestRejectSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Signal the SIP has been reviewed and rejected
     * reject_sip ingest
     */
    ingestRejectSip(requestParameters: IngestRejectSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for ingestReviewBatch without sending the request
     * @param {string} uuid Identifier of Batch to review
     * @param {ReviewBatchRequestBody} reviewBatchRequestBody 
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestReviewBatchRequestOpts(requestParameters: IngestReviewBatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Review a Batch awaiting user decision
     * @summary review_batch ingest
     * @param {string} uuid Identifier of Batch to review
     * @param {ReviewBatchRequestBody} reviewBatchRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestReviewBatchRaw(requestParameters: IngestReviewBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Review a Batch awaiting user decision
     * review_batch ingest
     */
    ingestReviewBatch(requestParameters: IngestReviewBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for ingestShowBatch without sending the request
     * @param {string} uuid Identifier of Batch to show
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestShowBatchRequestOpts(requestParameters: IngestShowBatchRequest): Promise<runtime.RequestOpts>;

    /**
     * Show Batch by UUID
     * @summary show_batch ingest
     * @param {string} uuid Identifier of Batch to show
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestShowBatchRaw(requestParameters: IngestShowBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestBatch>>;

    /**
     * Show Batch by UUID
     * show_batch ingest
     */
    ingestShowBatch(requestParameters: IngestShowBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestBatch>;

    /**
     * Creates request options for ingestShowSip without sending the request
     * @param {string} uuid Identifier of SIP to show
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestShowSipRequestOpts(requestParameters: IngestShowSipRequest): Promise<runtime.RequestOpts>;

    /**
     * Show SIP by ID
     * @summary show_sip ingest
     * @param {string} uuid Identifier of SIP to show
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestShowSipRaw(requestParameters: IngestShowSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestSip>>;

    /**
     * Show SIP by ID
     * show_sip ingest
     */
    ingestShowSip(requestParameters: IngestShowSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestSip>;

    /**
     * Creates request options for ingestShowSipDecision without sending the request
     * @param {string} uuid Identifier of SIP to look up
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestShowSipDecisionRequestOpts(requestParameters: IngestShowSipDecisionRequest): Promise<runtime.RequestOpts>;

    /**
     * Show the active child workflow decision request for a SIP
     * @summary show_sip_decision ingest
     * @param {string} uuid Identifier of SIP to look up
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestShowSipDecisionRaw(requestParameters: IngestShowSipDecisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestSipDecision>>;

    /**
     * Show the active child workflow decision request for a SIP
     * show_sip_decision ingest
     */
    ingestShowSipDecision(requestParameters: IngestShowSipDecisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestSipDecision>;

    /**
     * Creates request options for ingestSubmitSipDecision without sending the request
     * @param {string} uuid Identifier of SIP to look up
     * @param {SubmitSipDecisionRequestBody} submitSipDecisionRequestBody 
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestSubmitSipDecisionRequestOpts(requestParameters: IngestSubmitSipDecisionRequest): Promise<runtime.RequestOpts>;

    /**
     * Submit a selected child workflow decision option for a SIP
     * @summary submit_sip_decision ingest
     * @param {string} uuid Identifier of SIP to look up
     * @param {SubmitSipDecisionRequestBody} submitSipDecisionRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestSubmitSipDecisionRaw(requestParameters: IngestSubmitSipDecisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Submit a selected child workflow decision option for a SIP
     * submit_sip_decision ingest
     */
    ingestSubmitSipDecision(requestParameters: IngestSubmitSipDecisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for ingestUploadSip without sending the request
     * @param {string} [contentType] Content-Type header, must define value for multipart boundary.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestUploadSipRequestOpts(requestParameters: IngestUploadSipRequest): Promise<runtime.RequestOpts>;

    /**
     * Upload a SIP to trigger an ingest workflow
     * @summary upload_sip ingest
     * @param {string} [contentType] Content-Type header, must define value for multipart boundary.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IngestApiInterface
     */
    ingestUploadSipRaw(requestParameters: IngestUploadSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddSipResponseBody>>;

    /**
     * Upload a SIP to trigger an ingest workflow
     * upload_sip ingest
     */
    ingestUploadSip(requestParameters: IngestUploadSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddSipResponseBody>;

}

/**
 * 
 */
export class IngestApi extends runtime.BaseAPI implements IngestApiInterface {

    /**
     * Creates request options for ingestAddBatch without sending the request
     */
    async ingestAddBatchRequestOpts(requestParameters: IngestAddBatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['addBatchRequestBody'] == null) {
            throw new runtime.RequiredError(
                'addBatchRequestBody',
                'Required parameter "addBatchRequestBody" was null or undefined when calling ingestAddBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:batches:create"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/batches`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddBatchRequestBodyToJSON(requestParameters['addBatchRequestBody']),
        };
    }

    /**
     * Ingest a Batch from a SIP Source
     * add_batch ingest
     */
    async ingestAddBatchRaw(requestParameters: IngestAddBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddSipResponseBody>> {
        const requestOptions = await this.ingestAddBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddSipResponseBodyFromJSON(jsonValue));
    }

    /**
     * Ingest a Batch from a SIP Source
     * add_batch ingest
     */
    async ingestAddBatch(requestParameters: IngestAddBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddSipResponseBody> {
        const response = await this.ingestAddBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestAddSip without sending the request
     */
    async ingestAddSipRequestOpts(requestParameters: IngestAddSipRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sourceId'] == null) {
            throw new runtime.RequiredError(
                'sourceId',
                'Required parameter "sourceId" was null or undefined when calling ingestAddSip().'
            );
        }

        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling ingestAddSip().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sourceId'] != null) {
            queryParameters['source_id'] = requestParameters['sourceId'];
        }

        if (requestParameters['key'] != null) {
            queryParameters['key'] = requestParameters['key'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:sips:create"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/sips`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Ingest a SIP from a SIP Source
     * add_sip ingest
     */
    async ingestAddSipRaw(requestParameters: IngestAddSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddSipResponseBody>> {
        const requestOptions = await this.ingestAddSipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddSipResponseBodyFromJSON(jsonValue));
    }

    /**
     * Ingest a SIP from a SIP Source
     * add_sip ingest
     */
    async ingestAddSip(requestParameters: IngestAddSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddSipResponseBody> {
        const response = await this.ingestAddSipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestConfirmSip without sending the request
     */
    async ingestConfirmSipRequestOpts(requestParameters: IngestConfirmSipRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling ingestConfirmSip().'
            );
        }

        if (requestParameters['confirmSipRequestBody'] == null) {
            throw new runtime.RequiredError(
                'confirmSipRequestBody',
                'Required parameter "confirmSipRequestBody" was null or undefined when calling ingestConfirmSip().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:sips:review"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/sips/{uuid}/confirm`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmSipRequestBodyToJSON(requestParameters['confirmSipRequestBody']),
        };
    }

    /**
     * Signal the SIP has been reviewed and accepted
     * confirm_sip ingest
     */
    async ingestConfirmSipRaw(requestParameters: IngestConfirmSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.ingestConfirmSipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Signal the SIP has been reviewed and accepted
     * confirm_sip ingest
     */
    async ingestConfirmSip(requestParameters: IngestConfirmSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestConfirmSipRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for ingestDownloadSip without sending the request
     */
    async ingestDownloadSipRequestOpts(requestParameters: IngestDownloadSipRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling ingestDownloadSip().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ingest/sips/{uuid}/download`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Download the failed package related to a SIP. It will be the original SIP or the transformed PIP, based on the SIP\'s `failed_as` value.
     * download_sip ingest
     */
    async ingestDownloadSipRaw(requestParameters: IngestDownloadSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.ingestDownloadSipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Download the failed package related to a SIP. It will be the original SIP or the transformed PIP, based on the SIP\'s `failed_as` value.
     * download_sip ingest
     */
    async ingestDownloadSip(requestParameters: IngestDownloadSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.ingestDownloadSipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestDownloadSipRequest without sending the request
     */
    async ingestDownloadSipRequestRequestOpts(requestParameters: IngestDownloadSipRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling ingestDownloadSipRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:sips:download"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/sips/{uuid}/download`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Request access to SIP download
     * download_sip_request ingest
     */
    async ingestDownloadSipRequestRaw(requestParameters: IngestDownloadSipRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.ingestDownloadSipRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Request access to SIP download
     * download_sip_request ingest
     */
    async ingestDownloadSipRequest(requestParameters: IngestDownloadSipRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestDownloadSipRequestRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for ingestListBatches without sending the request
     */
    async ingestListBatchesRequestOpts(requestParameters: IngestListBatchesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['identifier'] != null) {
            queryParameters['identifier'] = requestParameters['identifier'];
        }

        if (requestParameters['earliestCreatedTime'] != null) {
            queryParameters['earliest_created_time'] = (requestParameters['earliestCreatedTime'] as any).toISOString();
        }

        if (requestParameters['latestCreatedTime'] != null) {
            queryParameters['latest_created_time'] = (requestParameters['latestCreatedTime'] as any).toISOString();
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['uploaderUuid'] != null) {
            queryParameters['uploader_uuid'] = requestParameters['uploaderUuid'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:batches:list"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/batches`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all ingested Batches
     * list_batches ingest
     */
    async ingestListBatchesRaw(requestParameters: IngestListBatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestBatches>> {
        const requestOptions = await this.ingestListBatchesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroIngestBatchesFromJSON(jsonValue));
    }

    /**
     * List all ingested Batches
     * list_batches ingest
     */
    async ingestListBatches(requestParameters: IngestListBatchesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestBatches> {
        const response = await this.ingestListBatchesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestListSipSourceObjects without sending the request
     */
    async ingestListSipSourceObjectsRequestOpts(requestParameters: IngestListSipSourceObjectsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling ingestListSipSourceObjects().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:sipsources:objects:list"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/sip-sources/{uuid}/objects`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the objects in a SIP source
     * list_sip_source_objects ingest
     */
    async ingestListSipSourceObjectsRaw(requestParameters: IngestListSipSourceObjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestSipsourceObjects>> {
        const requestOptions = await this.ingestListSipSourceObjectsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroIngestSipsourceObjectsFromJSON(jsonValue));
    }

    /**
     * List the objects in a SIP source
     * list_sip_source_objects ingest
     */
    async ingestListSipSourceObjects(requestParameters: IngestListSipSourceObjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestSipsourceObjects> {
        const response = await this.ingestListSipSourceObjectsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestListSipWorkflows without sending the request
     */
    async ingestListSipWorkflowsRequestOpts(requestParameters: IngestListSipWorkflowsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling ingestListSipWorkflows().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:sips:workflows:list"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/sips/{uuid}/workflows`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all workflows for a SIP
     * list_sip_workflows ingest
     */
    async ingestListSipWorkflowsRaw(requestParameters: IngestListSipWorkflowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestSipWorkflows>> {
        const requestOptions = await this.ingestListSipWorkflowsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroIngestSipWorkflowsFromJSON(jsonValue));
    }

    /**
     * List all workflows for a SIP
     * list_sip_workflows ingest
     */
    async ingestListSipWorkflows(requestParameters: IngestListSipWorkflowsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestSipWorkflows> {
        const response = await this.ingestListSipWorkflowsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestListSips without sending the request
     */
    async ingestListSipsRequestOpts(requestParameters: IngestListSipsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['aipUuid'] != null) {
            queryParameters['aip_uuid'] = requestParameters['aipUuid'];
        }

        if (requestParameters['earliestCreatedTime'] != null) {
            queryParameters['earliest_created_time'] = (requestParameters['earliestCreatedTime'] as any).toISOString();
        }

        if (requestParameters['latestCreatedTime'] != null) {
            queryParameters['latest_created_time'] = (requestParameters['latestCreatedTime'] as any).toISOString();
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['uploaderUuid'] != null) {
            queryParameters['uploader_uuid'] = requestParameters['uploaderUuid'];
        }

        if (requestParameters['batchUuid'] != null) {
            queryParameters['batch_uuid'] = requestParameters['batchUuid'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:sips:list"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/sips`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all ingested SIPs
     * list_sips ingest
     */
    async ingestListSipsRaw(requestParameters: IngestListSipsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestSips>> {
        const requestOptions = await this.ingestListSipsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroIngestSipsFromJSON(jsonValue));
    }

    /**
     * List all ingested SIPs
     * list_sips ingest
     */
    async ingestListSips(requestParameters: IngestListSipsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestSips> {
        const response = await this.ingestListSipsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestListUsers without sending the request
     */
    async ingestListUsersRequestOpts(requestParameters: IngestListUsersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:users:list"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/users`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all users
     * list_users ingest
     */
    async ingestListUsersRaw(requestParameters: IngestListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestUsers>> {
        const requestOptions = await this.ingestListUsersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroIngestUsersFromJSON(jsonValue));
    }

    /**
     * List all users
     * list_users ingest
     */
    async ingestListUsers(requestParameters: IngestListUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestUsers> {
        const response = await this.ingestListUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestMonitor without sending the request
     */
    async ingestMonitorRequestOpts(requestParameters: IngestMonitorRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ingest/monitor`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtain access to the /monitor WebSocket
     * monitor ingest
     */
    async ingestMonitorRaw(requestParameters: IngestMonitorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.ingestMonitorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Obtain access to the /monitor WebSocket
     * monitor ingest
     */
    async ingestMonitor(requestParameters: IngestMonitorRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestMonitorRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for ingestMonitorRequest without sending the request
     */
    async ingestMonitorRequestRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/monitor`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Request access to the /monitor WebSocket
     * monitor_request ingest
     */
    async ingestMonitorRequestRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.ingestMonitorRequestRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Request access to the /monitor WebSocket
     * monitor_request ingest
     */
    async ingestMonitorRequest(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestMonitorRequestRaw(initOverrides);
    }

    /**
     * Creates request options for ingestRejectSip without sending the request
     */
    async ingestRejectSipRequestOpts(requestParameters: IngestRejectSipRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling ingestRejectSip().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:sips:review"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/sips/{uuid}/reject`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Signal the SIP has been reviewed and rejected
     * reject_sip ingest
     */
    async ingestRejectSipRaw(requestParameters: IngestRejectSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.ingestRejectSipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Signal the SIP has been reviewed and rejected
     * reject_sip ingest
     */
    async ingestRejectSip(requestParameters: IngestRejectSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestRejectSipRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for ingestReviewBatch without sending the request
     */
    async ingestReviewBatchRequestOpts(requestParameters: IngestReviewBatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling ingestReviewBatch().'
            );
        }

        if (requestParameters['reviewBatchRequestBody'] == null) {
            throw new runtime.RequiredError(
                'reviewBatchRequestBody',
                'Required parameter "reviewBatchRequestBody" was null or undefined when calling ingestReviewBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:batches:review"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/batches/{uuid}/review`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReviewBatchRequestBodyToJSON(requestParameters['reviewBatchRequestBody']),
        };
    }

    /**
     * Review a Batch awaiting user decision
     * review_batch ingest
     */
    async ingestReviewBatchRaw(requestParameters: IngestReviewBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.ingestReviewBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Review a Batch awaiting user decision
     * review_batch ingest
     */
    async ingestReviewBatch(requestParameters: IngestReviewBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestReviewBatchRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for ingestShowBatch without sending the request
     */
    async ingestShowBatchRequestOpts(requestParameters: IngestShowBatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling ingestShowBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:batches:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/batches/{uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Show Batch by UUID
     * show_batch ingest
     */
    async ingestShowBatchRaw(requestParameters: IngestShowBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestBatch>> {
        const requestOptions = await this.ingestShowBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroIngestBatchFromJSON(jsonValue));
    }

    /**
     * Show Batch by UUID
     * show_batch ingest
     */
    async ingestShowBatch(requestParameters: IngestShowBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestBatch> {
        const response = await this.ingestShowBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestShowSip without sending the request
     */
    async ingestShowSipRequestOpts(requestParameters: IngestShowSipRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling ingestShowSip().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:sips:read"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/sips/{uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Show SIP by ID
     * show_sip ingest
     */
    async ingestShowSipRaw(requestParameters: IngestShowSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestSip>> {
        const requestOptions = await this.ingestShowSipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroIngestSipFromJSON(jsonValue));
    }

    /**
     * Show SIP by ID
     * show_sip ingest
     */
    async ingestShowSip(requestParameters: IngestShowSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestSip> {
        const response = await this.ingestShowSipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestShowSipDecision without sending the request
     */
    async ingestShowSipDecisionRequestOpts(requestParameters: IngestShowSipDecisionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling ingestShowSipDecision().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:sips:decision"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/sips/{uuid}/decision`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Show the active child workflow decision request for a SIP
     * show_sip_decision ingest
     */
    async ingestShowSipDecisionRaw(requestParameters: IngestShowSipDecisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnduroIngestSipDecision>> {
        const requestOptions = await this.ingestShowSipDecisionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnduroIngestSipDecisionFromJSON(jsonValue));
    }

    /**
     * Show the active child workflow decision request for a SIP
     * show_sip_decision ingest
     */
    async ingestShowSipDecision(requestParameters: IngestShowSipDecisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnduroIngestSipDecision> {
        const response = await this.ingestShowSipDecisionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestSubmitSipDecision without sending the request
     */
    async ingestSubmitSipDecisionRequestOpts(requestParameters: IngestSubmitSipDecisionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling ingestSubmitSipDecision().'
            );
        }

        if (requestParameters['submitSipDecisionRequestBody'] == null) {
            throw new runtime.RequiredError(
                'submitSipDecisionRequestBody',
                'Required parameter "submitSipDecisionRequestBody" was null or undefined when calling ingestSubmitSipDecision().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:sips:decision"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/sips/{uuid}/decision`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitSipDecisionRequestBodyToJSON(requestParameters['submitSipDecisionRequestBody']),
        };
    }

    /**
     * Submit a selected child workflow decision option for a SIP
     * submit_sip_decision ingest
     */
    async ingestSubmitSipDecisionRaw(requestParameters: IngestSubmitSipDecisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.ingestSubmitSipDecisionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Submit a selected child workflow decision option for a SIP
     * submit_sip_decision ingest
     */
    async ingestSubmitSipDecision(requestParameters: IngestSubmitSipDecisionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestSubmitSipDecisionRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for ingestUploadSip without sending the request
     */
    async ingestUploadSipRequestOpts(requestParameters: IngestUploadSipRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['contentType'] != null) {
            headerParameters['Content-Type'] = String(requestParameters['contentType']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("jwt_header_Authorization", ["ingest:sips:upload"]);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ingest/sips/upload`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Upload a SIP to trigger an ingest workflow
     * upload_sip ingest
     */
    async ingestUploadSipRaw(requestParameters: IngestUploadSipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddSipResponseBody>> {
        const requestOptions = await this.ingestUploadSipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddSipResponseBodyFromJSON(jsonValue));
    }

    /**
     * Upload a SIP to trigger an ingest workflow
     * upload_sip ingest
     */
    async ingestUploadSip(requestParameters: IngestUploadSipRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddSipResponseBody> {
        const response = await this.ingestUploadSipRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const IngestListBatchesStatusEnum = {
    Queued: 'queued',
    Processing: 'processing',
    Pending: 'pending',
    Ingested: 'ingested',
    Canceled: 'canceled',
    Failed: 'failed'
} as const;
export type IngestListBatchesStatusEnum = typeof IngestListBatchesStatusEnum[keyof typeof IngestListBatchesStatusEnum];
/**
 * @export
 */
export const IngestListSipsStatusEnum = {
    Error: 'error',
    Failed: 'failed',
    Queued: 'queued',
    Processing: 'processing',
    Pending: 'pending',
    Ingested: 'ingested',
    Validated: 'validated',
    Canceled: 'canceled'
} as const;
export type IngestListSipsStatusEnum = typeof IngestListSipsStatusEnum[keyof typeof IngestListSipsStatusEnum];
