apiVersion: v1
kind: Secret
metadata:
  name: enduro-am-secret
type: Opaque
stringData:
  api_user: "artefactual"
  api_key: ""
  sftp_host: "localhost"
  sftp_user: "artefactual"
  known_hosts: ""
  id_ed25519: ""
