apiVersion: v1
kind: Secret
metadata:
  name: enduro-secret
type: Opaque
stringData:
  oidc-enabled: "true"
  oidc-provider-url: http://keycloak:7470/realms/artefactual
  oidc-redirect-url: http://localhost:8080/user/signin-callback
  oidc-client-id: enduro
  oidc-extra-scopes: enduro
  oidc-abac-enabled: "true"
  oidc-abac-claim-path: enduro
  oidc-abac-claim-path-separator: ""
  oidc-abac-claim-value-prefix: ""
