apiVersion: v1
kind: Secret
metadata:
  name: enduro-secret
type: Opaque
stringData:
  oidc-provider-url: http://dex:5556
  oidc-redirect-url: http://localhost:8080/user/signin-callback
  oidc-client-id: enduro-dashboard
  oidc-audience-client-id: enduro
  oidc-client-secret: ZXhhbXBsZS1hcHAtc2VjcmV0
