apiVersion: v1
kind: Secret
metadata:
  name: enduro-secret
type: Opaque
stringData:
  oidc-provider-url: http://keycloak:7470/realms/enduro
  oidc-redirect-url: http://localhost:8080/user/signin-callback
  oidc-client-id: enduro
  oidc-extra-scopes: enduro
