apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      enableServiceLinks: false
      containers:
        - name: ldap
          image: osixia/openldap:1.5.0
          env:
            - name: LDAP_TLS_VERIFY_CLIENT
              value: try
            - name: LDAP_SEED_INTERNAL_LDIF_PATH
              value: /tmp/ldif
            - name: LDAPS_PORT
              value: "1636"
          ports:
            - containerPort: 1636
          volumeMounts:
            - name: config
              mountPath: /tmp/ldif
              readOnly: true
          resources: {}
      volumes:
        - name: config
          configMap:
            name: ldap-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  selector:
    app: ldap
  ports:
    - port: 636
      targetPort: 1636
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-configmap
data:
  config-ldap.ldif: |
    dn: ou=People,dc=example,dc=org
    objectClass: organizationalUnit
    ou: People

    dn: cn=admin,ou=People,dc=example,dc=org
    objectClass: person
    objectClass: inetOrgPerson
    sn: admin
    cn: admin
    mail: admin@example.com
    userpassword: admin
