apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  user: minio
  password: minio123
  oidc-url: http://keycloak:7470/realms/enduro/.well-known/openid-configuration
  oidc-client-id: minio
  oidc-client-secret: K5do3lZeHEzR3ajzCEudH4OGe7KWUmfe
  oidc-scopes: openid email profile minio
  oidc-claim: minio
  redirect-url: http://localhost:7460
