apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enduro-a3m
spec:
  template:
    spec:
      containers:
        - name: a3m
          env:
            - name: A3M_DEBUG
              value: "true"
