apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enduro
spec:
  template:
    spec:
      containers:
        - name: enduro
          env:
            - name: ENDURO_PRESERVATION_TASKQUEUE
              value: "a3m"
            - name: ENDURO_INGEST_STORAGE_DEFAULTPERMANENTLOCATIONID
              value: "f2cc963f-c14d-4eaa-b950-bd207189a1f1"
