apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enduro
spec:
  template:
    spec:
      containers:
        - name: enduro
          env:
            - name: ENDURO_PRESERVATION_TASKQUEUE
              value: "am"
            - name: ENDURO_STORAGE_DEFAULTPERMANENTLOCATIONID
              valueFrom:
                secretKeyRef:
                  name: enduro-am-secret
                  key: amss_location_id
