/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AIP not found.
 * @export
 * @interface AIPNotFound
 */
export interface AIPNotFound {
    /**
     * Message of error
     * @type {string}
     * @memberof AIPNotFound
     */
    message: string;
    /**
     * Identifier of missing AIP
     * @type {string}
     * @memberof AIPNotFound
     */
    uuid: string;
}

/**
 * Check if a given object implements the AIPNotFound interface.
 */
export function instanceOfAIPNotFound(value: object): value is AIPNotFound {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    return true;
}

export function AIPNotFoundFromJSON(json: any): AIPNotFound {
    return AIPNotFoundFromJSONTyped(json, false);
}

export function AIPNotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): AIPNotFound {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'uuid': json['uuid'],
    };
}

export function AIPNotFoundToJSON(json: any): AIPNotFound {
    return AIPNotFoundToJSONTyped(json, false);
}

export function AIPNotFoundToJSONTyped(value?: AIPNotFound | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'uuid': value['uuid'],
    };
}

