/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EnduroIngestBatch } from './EnduroIngestBatch';
import {
    EnduroIngestBatchFromJSON,
    EnduroIngestBatchFromJSONTyped,
    EnduroIngestBatchToJSON,
} from './EnduroIngestBatch';

/**
 * 
 * @export
 * @interface BatchUpdatedEvent
 */
export interface BatchUpdatedEvent {
    /**
     * 
     * @type {EnduroIngestBatch}
     * @memberof BatchUpdatedEvent
     */
    item: EnduroIngestBatch;
    /**
     * Identifier of Batch
     * @type {string}
     * @memberof BatchUpdatedEvent
     */
    uuid: string;
}

/**
 * Check if a given object implements the BatchUpdatedEvent interface.
 */
export function instanceOfBatchUpdatedEvent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "item" in value;
    isInstance = isInstance && "uuid" in value;

    return isInstance;
}

export function BatchUpdatedEventFromJSON(json: any): BatchUpdatedEvent {
    return BatchUpdatedEventFromJSONTyped(json, false);
}

export function BatchUpdatedEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchUpdatedEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'item': EnduroIngestBatchFromJSON(json['item']),
        'uuid': json['uuid'],
    };
}

export function BatchUpdatedEventToJSON(value?: BatchUpdatedEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item': EnduroIngestBatchToJSON(value.item),
        'uuid': value.uuid,
    };
}

