/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EnduroStoredPackageResponseBody,
    EnduroStoredPackageResponseBodyFromJSON,
    EnduroStoredPackageResponseBodyFromJSONTyped,
    EnduroStoredPackageResponseBodyToJSON,
} from './EnduroStoredPackageResponseBody';

/**
 * EnduroPackage-Created-EventResponseBody result type (default view)
 * @export
 * @interface EnduroPackageCreatedEventResponseBody
 */
export interface EnduroPackageCreatedEventResponseBody {
    /**
     * Identifier of package
     * @type {number}
     * @memberof EnduroPackageCreatedEventResponseBody
     */
    id: number;
    /**
     * 
     * @type {EnduroStoredPackageResponseBody}
     * @memberof EnduroPackageCreatedEventResponseBody
     */
    item: EnduroStoredPackageResponseBody;
}

export function EnduroPackageCreatedEventResponseBodyFromJSON(json: any): EnduroPackageCreatedEventResponseBody {
    return EnduroPackageCreatedEventResponseBodyFromJSONTyped(json, false);
}

export function EnduroPackageCreatedEventResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroPackageCreatedEventResponseBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'item': EnduroStoredPackageResponseBodyFromJSON(json['item']),
    };
}

export function EnduroPackageCreatedEventResponseBodyToJSON(value?: EnduroPackageCreatedEventResponseBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'item': EnduroStoredPackageResponseBodyToJSON(value.item),
    };
}

