/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * PreservationAction describes a preservation action. (default view)
 * @export
 * @interface EnduroPackagePreservationActionsActionResponseBody
 */
export interface EnduroPackagePreservationActionsActionResponseBody {
    /**
     * 
     * @type {string}
     * @memberof EnduroPackagePreservationActionsActionResponseBody
     */
    actionId: string;
    /**
     * 
     * @type {Date}
     * @memberof EnduroPackagePreservationActionsActionResponseBody
     */
    completedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof EnduroPackagePreservationActionsActionResponseBody
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EnduroPackagePreservationActionsActionResponseBody
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof EnduroPackagePreservationActionsActionResponseBody
     */
    startedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof EnduroPackagePreservationActionsActionResponseBody
     */
    status: EnduroPackagePreservationActionsActionResponseBodyStatusEnum;
}


/**
 * @export
 */
export const EnduroPackagePreservationActionsActionResponseBodyStatusEnum = {
    Unspecified: 'unspecified',
    Complete: 'complete',
    Processing: 'processing',
    Failed: 'failed'
} as const;
export type EnduroPackagePreservationActionsActionResponseBodyStatusEnum = typeof EnduroPackagePreservationActionsActionResponseBodyStatusEnum[keyof typeof EnduroPackagePreservationActionsActionResponseBodyStatusEnum];


export function EnduroPackagePreservationActionsActionResponseBodyFromJSON(json: any): EnduroPackagePreservationActionsActionResponseBody {
    return EnduroPackagePreservationActionsActionResponseBodyFromJSONTyped(json, false);
}

export function EnduroPackagePreservationActionsActionResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroPackagePreservationActionsActionResponseBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actionId': json['action_id'],
        'completedAt': !exists(json, 'completed_at') ? undefined : (new Date(json['completed_at'])),
        'id': json['id'],
        'name': json['name'],
        'startedAt': (new Date(json['started_at'])),
        'status': json['status'],
    };
}

export function EnduroPackagePreservationActionsActionResponseBodyToJSON(value?: EnduroPackagePreservationActionsActionResponseBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action_id': value.actionId,
        'completed_at': value.completedAt === undefined ? undefined : (value.completedAt.toISOString()),
        'id': value.id,
        'name': value.name,
        'started_at': (value.startedAt.toISOString()),
        'status': value.status,
    };
}

