/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * SIPDecision describes an active child workflow decision request.
 * @export
 * @interface EnduroIngestSipDecision
 */
export interface EnduroIngestSipDecision {
    /**
     * 
     * @type {string}
     * @memberof EnduroIngestSipDecision
     */
    message: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EnduroIngestSipDecision
     */
    options: Array<string>;
}

/**
 * Check if a given object implements the EnduroIngestSipDecision interface.
 */
export function instanceOfEnduroIngestSipDecision(value: object): value is EnduroIngestSipDecision {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function EnduroIngestSipDecisionFromJSON(json: any): EnduroIngestSipDecision {
    return EnduroIngestSipDecisionFromJSONTyped(json, false);
}

export function EnduroIngestSipDecisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroIngestSipDecision {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'options': json['options'],
    };
}

export function EnduroIngestSipDecisionToJSON(json: any): EnduroIngestSipDecision {
    return EnduroIngestSipDecisionToJSONTyped(json, false);
}

export function EnduroIngestSipDecisionToJSONTyped(value?: EnduroIngestSipDecision | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'options': value['options'],
    };
}

