/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * EnduroPackage-Deleted-EventResponseBody result type (default view)
 * @export
 * @interface EnduroPackageDeletedEventResponseBody
 */
export interface EnduroPackageDeletedEventResponseBody {
    /**
     * Identifier of package
     * @type {number}
     * @memberof EnduroPackageDeletedEventResponseBody
     */
    id: number;
}

export function EnduroPackageDeletedEventResponseBodyFromJSON(json: any): EnduroPackageDeletedEventResponseBody {
    return EnduroPackageDeletedEventResponseBodyFromJSONTyped(json, false);
}

export function EnduroPackageDeletedEventResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnduroPackageDeletedEventResponseBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function EnduroPackageDeletedEventResponseBodyToJSON(value?: EnduroPackageDeletedEventResponseBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

