/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BatchUpdatedEvent } from './BatchUpdatedEvent';
import {
    BatchUpdatedEventFromJSON,
    BatchUpdatedEventFromJSONTyped,
    BatchUpdatedEventToJSON,
    BatchUpdatedEventToJSONTyped,
} from './BatchUpdatedEvent';

/**
 * 
 * @export
 * @interface IngestEventValueAnyOf9
 */
export interface IngestEventValueAnyOf9 {
    /**
     * 
     * @type {IngestEventValueAnyOf9TypeEnum}
     * @memberof IngestEventValueAnyOf9
     */
    type: IngestEventValueAnyOf9TypeEnum;
    /**
     * 
     * @type {BatchUpdatedEvent}
     * @memberof IngestEventValueAnyOf9
     */
    value: BatchUpdatedEvent;
}


/**
 * @export
 */
export const IngestEventValueAnyOf9TypeEnum = {
    BatchUpdatedEvent: 'batch_updated_event'
} as const;
export type IngestEventValueAnyOf9TypeEnum = typeof IngestEventValueAnyOf9TypeEnum[keyof typeof IngestEventValueAnyOf9TypeEnum];


/**
 * Check if a given object implements the IngestEventValueAnyOf9 interface.
 */
export function instanceOfIngestEventValueAnyOf9(value: object): value is IngestEventValueAnyOf9 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'batch_updated_event') return false;
    
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function IngestEventValueAnyOf9FromJSON(json: any): IngestEventValueAnyOf9 {
    return IngestEventValueAnyOf9FromJSONTyped(json, false);
}

export function IngestEventValueAnyOf9FromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestEventValueAnyOf9 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': BatchUpdatedEventFromJSON(json['value']),
    };
}

export function IngestEventValueAnyOf9ToJSON(json: any): IngestEventValueAnyOf9 {
    return IngestEventValueAnyOf9ToJSONTyped(json, false);
}

export function IngestEventValueAnyOf9ToJSONTyped(value?: IngestEventValueAnyOf9 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'value': BatchUpdatedEventToJSON(value['value']),
    };
}

