/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EnduroIngestSip } from './EnduroIngestSip';
import {
    EnduroIngestSipFromJSON,
    EnduroIngestSipFromJSONTyped,
    EnduroIngestSipToJSON,
} from './EnduroIngestSip';

/**
 * 
 * @export
 * @interface SIPCreatedEvent
 */
export interface SIPCreatedEvent {
    /**
     * Identifier of SIP
     * @type {number}
     * @memberof SIPCreatedEvent
     */
    id: number;
    /**
     * 
     * @type {EnduroIngestSip}
     * @memberof SIPCreatedEvent
     */
    item: EnduroIngestSip;
}

/**
 * Check if a given object implements the SIPCreatedEvent interface.
 */
export function instanceOfSIPCreatedEvent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "item" in value;

    return isInstance;
}

export function SIPCreatedEventFromJSON(json: any): SIPCreatedEvent {
    return SIPCreatedEventFromJSONTyped(json, false);
}

export function SIPCreatedEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SIPCreatedEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'item': EnduroIngestSipFromJSON(json['item']),
    };
}

export function SIPCreatedEventToJSON(value?: SIPCreatedEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'item': EnduroIngestSipToJSON(value.item),
    };
}

