/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnduroIngestSipTask } from './EnduroIngestSipTask';
import {
    EnduroIngestSipTaskFromJSON,
    EnduroIngestSipTaskFromJSONTyped,
    EnduroIngestSipTaskToJSON,
    EnduroIngestSipTaskToJSONTyped,
} from './EnduroIngestSipTask';

/**
 * 
 * @export
 * @interface SIPTaskCreatedEvent
 */
export interface SIPTaskCreatedEvent {
    /**
     * 
     * @type {EnduroIngestSipTask}
     * @memberof SIPTaskCreatedEvent
     */
    item: EnduroIngestSipTask;
    /**
     * Identifier of task
     * @type {string}
     * @memberof SIPTaskCreatedEvent
     */
    uuid: string;
}

/**
 * Check if a given object implements the SIPTaskCreatedEvent interface.
 */
export function instanceOfSIPTaskCreatedEvent(value: object): value is SIPTaskCreatedEvent {
    if (!('item' in value) || value['item'] === undefined) return false;
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    return true;
}

export function SIPTaskCreatedEventFromJSON(json: any): SIPTaskCreatedEvent {
    return SIPTaskCreatedEventFromJSONTyped(json, false);
}

export function SIPTaskCreatedEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SIPTaskCreatedEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'item': EnduroIngestSipTaskFromJSON(json['item']),
        'uuid': json['uuid'],
    };
}

export function SIPTaskCreatedEventToJSON(json: any): SIPTaskCreatedEvent {
    return SIPTaskCreatedEventToJSONTyped(json, false);
}

export function SIPTaskCreatedEventToJSONTyped(value?: SIPTaskCreatedEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item': EnduroIngestSipTaskToJSON(value['item']),
        'uuid': value['uuid'],
    };
}

