/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AIPLocationUpdatedEvent } from './AIPLocationUpdatedEvent';
import {
    AIPLocationUpdatedEventFromJSON,
    AIPLocationUpdatedEventFromJSONTyped,
    AIPLocationUpdatedEventToJSON,
    AIPLocationUpdatedEventToJSONTyped,
} from './AIPLocationUpdatedEvent';

/**
 * 
 * @export
 * @interface StorageEventValueAnyOf5
 */
export interface StorageEventValueAnyOf5 {
    /**
     * 
     * @type {StorageEventValueAnyOf5TypeEnum}
     * @memberof StorageEventValueAnyOf5
     */
    type: StorageEventValueAnyOf5TypeEnum;
    /**
     * 
     * @type {AIPLocationUpdatedEvent}
     * @memberof StorageEventValueAnyOf5
     */
    value: AIPLocationUpdatedEvent;
}


/**
 * @export
 */
export const StorageEventValueAnyOf5TypeEnum = {
    AipLocationUpdatedEvent: 'aip_location_updated_event'
} as const;
export type StorageEventValueAnyOf5TypeEnum = typeof StorageEventValueAnyOf5TypeEnum[keyof typeof StorageEventValueAnyOf5TypeEnum];


/**
 * Check if a given object implements the StorageEventValueAnyOf5 interface.
 */
export function instanceOfStorageEventValueAnyOf5(value: object): value is StorageEventValueAnyOf5 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'aip_location_updated_event') return false;
    
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function StorageEventValueAnyOf5FromJSON(json: any): StorageEventValueAnyOf5 {
    return StorageEventValueAnyOf5FromJSONTyped(json, false);
}

export function StorageEventValueAnyOf5FromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageEventValueAnyOf5 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'value': AIPLocationUpdatedEventFromJSON(json['value']),
    };
}

export function StorageEventValueAnyOf5ToJSON(json: any): StorageEventValueAnyOf5 {
    return StorageEventValueAnyOf5ToJSONTyped(json, false);
}

export function StorageEventValueAnyOf5ToJSONTyped(value?: StorageEventValueAnyOf5 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'value': AIPLocationUpdatedEventToJSON(value['value']),
    };
}

