/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageMonitorEventStorageEvent
 */
export interface StorageMonitorEventStorageEvent {
    /**
     * Union type name, one of:
     * - "storage_ping_event"
     * - "location_created_event"
     * - "location_updated_event"
     * - "aip_created_event"
     * - "aip_updated_event"
     * - "aip_workflow_created_event"
     * - "aip_workflow_updated_event"
     * - "aip_task_created_event"
     * - "aip_task_updated_event"
     * @type {string}
     * @memberof StorageMonitorEventStorageEvent
     */
    type: StorageMonitorEventStorageEventTypeEnum;
    /**
     * JSON encoded union value
     * @type {string}
     * @memberof StorageMonitorEventStorageEvent
     */
    value: string;
}


/**
 * @export
 */
export const StorageMonitorEventStorageEventTypeEnum = {
    StoragePingEvent: 'storage_ping_event',
    LocationCreatedEvent: 'location_created_event',
    LocationUpdatedEvent: 'location_updated_event',
    AipCreatedEvent: 'aip_created_event',
    AipUpdatedEvent: 'aip_updated_event',
    AipWorkflowCreatedEvent: 'aip_workflow_created_event',
    AipWorkflowUpdatedEvent: 'aip_workflow_updated_event',
    AipTaskCreatedEvent: 'aip_task_created_event',
    AipTaskUpdatedEvent: 'aip_task_updated_event'
} as const;
export type StorageMonitorEventStorageEventTypeEnum = typeof StorageMonitorEventStorageEventTypeEnum[keyof typeof StorageMonitorEventStorageEventTypeEnum];


/**
 * Check if a given object implements the StorageMonitorEventStorageEvent interface.
 */
export function instanceOfStorageMonitorEventStorageEvent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function StorageMonitorEventStorageEventFromJSON(json: any): StorageMonitorEventStorageEvent {
    return StorageMonitorEventStorageEventFromJSONTyped(json, false);
}

export function StorageMonitorEventStorageEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageMonitorEventStorageEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['Type'],
        'value': json['Value'],
    };
}

export function StorageMonitorEventStorageEventToJSON(value?: StorageMonitorEventStorageEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Type': value.type,
        'Value': value.value,
    };
}

