/* tslint:disable */
/* eslint-disable */
/**
 * Enduro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageUpdateRequestBody
 */
export interface StorageUpdateRequestBody {
    /**
     * 
     * @type {string}
     * @memberof StorageUpdateRequestBody
     */
    workflowId: string;
}

export function StorageUpdateRequestBodyFromJSON(json: any): StorageUpdateRequestBody {
    return StorageUpdateRequestBodyFromJSONTyped(json, false);
}

export function StorageUpdateRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageUpdateRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'workflowId': json['workflow_id'],
    };
}

export function StorageUpdateRequestBodyToJSON(value?: StorageUpdateRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'workflow_id': value.workflowId,
    };
}

