// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/artefactual-sdps/enduro/internal/storage/persistence/ent/db/aip"
	"github.com/artefactual-sdps/enduro/internal/storage/persistence/ent/db/deletionrequest"
	"github.com/artefactual-sdps/enduro/internal/storage/persistence/ent/db/predicate"
	"github.com/artefactual-sdps/enduro/internal/storage/persistence/ent/db/workflow"
)

// DeletionRequestQuery is the builder for querying DeletionRequest entities.
type DeletionRequestQuery struct {
	config
	ctx          *QueryContext
	order        []deletionrequest.OrderOption
	inters       []Interceptor
	predicates   []predicate.DeletionRequest
	withAip      *AIPQuery
	withWorkflow *WorkflowQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeletionRequestQuery builder.
func (_q *DeletionRequestQuery) Where(ps ...predicate.DeletionRequest) *DeletionRequestQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DeletionRequestQuery) Limit(limit int) *DeletionRequestQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DeletionRequestQuery) Offset(offset int) *DeletionRequestQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DeletionRequestQuery) Unique(unique bool) *DeletionRequestQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DeletionRequestQuery) Order(o ...deletionrequest.OrderOption) *DeletionRequestQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAip chains the current query on the "aip" edge.
func (_q *DeletionRequestQuery) QueryAip() *AIPQuery {
	query := (&AIPClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deletionrequest.Table, deletionrequest.FieldID, selector),
			sqlgraph.To(aip.Table, aip.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deletionrequest.AipTable, deletionrequest.AipColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkflow chains the current query on the "workflow" edge.
func (_q *DeletionRequestQuery) QueryWorkflow() *WorkflowQuery {
	query := (&WorkflowClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deletionrequest.Table, deletionrequest.FieldID, selector),
			sqlgraph.To(workflow.Table, workflow.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, deletionrequest.WorkflowTable, deletionrequest.WorkflowColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeletionRequest entity from the query.
// Returns a *NotFoundError when no DeletionRequest was found.
func (_q *DeletionRequestQuery) First(ctx context.Context) (*DeletionRequest, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deletionrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DeletionRequestQuery) FirstX(ctx context.Context) *DeletionRequest {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeletionRequest ID from the query.
// Returns a *NotFoundError when no DeletionRequest ID was found.
func (_q *DeletionRequestQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deletionrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DeletionRequestQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeletionRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeletionRequest entity is found.
// Returns a *NotFoundError when no DeletionRequest entities are found.
func (_q *DeletionRequestQuery) Only(ctx context.Context) (*DeletionRequest, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deletionrequest.Label}
	default:
		return nil, &NotSingularError{deletionrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DeletionRequestQuery) OnlyX(ctx context.Context) *DeletionRequest {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeletionRequest ID in the query.
// Returns a *NotSingularError when more than one DeletionRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DeletionRequestQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deletionrequest.Label}
	default:
		err = &NotSingularError{deletionrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DeletionRequestQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeletionRequests.
func (_q *DeletionRequestQuery) All(ctx context.Context) ([]*DeletionRequest, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeletionRequest, *DeletionRequestQuery]()
	return withInterceptors[[]*DeletionRequest](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DeletionRequestQuery) AllX(ctx context.Context) []*DeletionRequest {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeletionRequest IDs.
func (_q *DeletionRequestQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(deletionrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DeletionRequestQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DeletionRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DeletionRequestQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DeletionRequestQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DeletionRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DeletionRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeletionRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DeletionRequestQuery) Clone() *DeletionRequestQuery {
	if _q == nil {
		return nil
	}
	return &DeletionRequestQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]deletionrequest.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.DeletionRequest{}, _q.predicates...),
		withAip:      _q.withAip.Clone(),
		withWorkflow: _q.withWorkflow.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAip tells the query-builder to eager-load the nodes that are connected to
// the "aip" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DeletionRequestQuery) WithAip(opts ...func(*AIPQuery)) *DeletionRequestQuery {
	query := (&AIPClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAip = query
	return _q
}

// WithWorkflow tells the query-builder to eager-load the nodes that are connected to
// the "workflow" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DeletionRequestQuery) WithWorkflow(opts ...func(*WorkflowQuery)) *DeletionRequestQuery {
	query := (&WorkflowClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWorkflow = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeletionRequest.Query().
//		GroupBy(deletionrequest.FieldUUID).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (_q *DeletionRequestQuery) GroupBy(field string, fields ...string) *DeletionRequestGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeletionRequestGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = deletionrequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//	}
//
//	client.DeletionRequest.Query().
//		Select(deletionrequest.FieldUUID).
//		Scan(ctx, &v)
func (_q *DeletionRequestQuery) Select(fields ...string) *DeletionRequestSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DeletionRequestSelect{DeletionRequestQuery: _q}
	sbuild.label = deletionrequest.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeletionRequestSelect configured with the given aggregations.
func (_q *DeletionRequestQuery) Aggregate(fns ...AggregateFunc) *DeletionRequestSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DeletionRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !deletionrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DeletionRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeletionRequest, error) {
	var (
		nodes       = []*DeletionRequest{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withAip != nil,
			_q.withWorkflow != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeletionRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeletionRequest{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAip; query != nil {
		if err := _q.loadAip(ctx, query, nodes, nil,
			func(n *DeletionRequest, e *AIP) { n.Edges.Aip = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWorkflow; query != nil {
		if err := _q.loadWorkflow(ctx, query, nodes, nil,
			func(n *DeletionRequest, e *Workflow) { n.Edges.Workflow = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DeletionRequestQuery) loadAip(ctx context.Context, query *AIPQuery, nodes []*DeletionRequest, init func(*DeletionRequest), assign func(*DeletionRequest, *AIP)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DeletionRequest)
	for i := range nodes {
		fk := nodes[i].AipID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(aip.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "aip_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DeletionRequestQuery) loadWorkflow(ctx context.Context, query *WorkflowQuery, nodes []*DeletionRequest, init func(*DeletionRequest), assign func(*DeletionRequest, *Workflow)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DeletionRequest)
	for i := range nodes {
		fk := nodes[i].WorkflowID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workflow.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workflow_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *DeletionRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DeletionRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deletionrequest.Table, deletionrequest.Columns, sqlgraph.NewFieldSpec(deletionrequest.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deletionrequest.FieldID)
		for i := range fields {
			if fields[i] != deletionrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAip != nil {
			_spec.Node.AddColumnOnce(deletionrequest.FieldAipID)
		}
		if _q.withWorkflow != nil {
			_spec.Node.AddColumnOnce(deletionrequest.FieldWorkflowID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DeletionRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(deletionrequest.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = deletionrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeletionRequestGroupBy is the group-by builder for DeletionRequest entities.
type DeletionRequestGroupBy struct {
	selector
	build *DeletionRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DeletionRequestGroupBy) Aggregate(fns ...AggregateFunc) *DeletionRequestGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DeletionRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeletionRequestQuery, *DeletionRequestGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DeletionRequestGroupBy) sqlScan(ctx context.Context, root *DeletionRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeletionRequestSelect is the builder for selecting fields of DeletionRequest entities.
type DeletionRequestSelect struct {
	*DeletionRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DeletionRequestSelect) Aggregate(fns ...AggregateFunc) *DeletionRequestSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DeletionRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeletionRequestQuery, *DeletionRequestSelect](ctx, _s.DeletionRequestQuery, _s, _s.inters, v)
}

func (_s *DeletionRequestSelect) sqlScan(ctx context.Context, root *DeletionRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
