site_name: "Enduro SDPS"
site_url: "https://enduro.readthedocs.io"
site_description: "Enduro SDPS documentation site."
site_author: "Artefactual Systems Inc."
repo_url: "https://github.com/artefactual-sdps/enduro"
edit_uri: "blob/main/docs/"
docs_dir: "src"
site_dir: "site"

nav:
  - "Home": "index.md"
  - "User manual": "user-manual/"
  - "Administrator manual": "admin-manual/"
  - "Developer manual": "dev-manual/"
  - "About":
      - "Repository": "https://github.com/artefactual-sdps/enduro"
      - "Issues": "https://github.com/artefactual-sdps/enduro/issues"
      - "License": "https://github.com/artefactual-sdps/enduro/blob/main/LICENSE"

markdown_extensions:
  - admonition

plugins:
  - autorefs
  - literate-nav:
      nav_file: README.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - json
    - go
