site_name: "Enduro SDPS"
site_url: "https://enduro.readthedocs.io"
site_description: "Enduro SDPS documentation site."
site_author: "Artefactual Systems Inc."
repo_url: "https://github.com/artefactual-sdps/enduro"
edit_uri: "blob/main/docs/src/"
docs_dir: "src"
site_dir: "site"

nav:
  - Home: index.md
  - User manual:
      - Overview and first steps: user-manual/overview.md
      - Ingest:
          - user-manual/ingest/index.md
          - Submitting content: user-manual/ingest/submitting-content.md
          - Managing ingest workflows: user-manual/ingest/managing-ingest-workflows.md
          - Searching and browsing: user-manual/ingest/search-browse.md
      - Storage:
          - user-manual/storage/index.md
          - Browse and manage locations: user-manual/storage/manage-locations.md
          - Search and browse AIPs: user-manual/storage/browse-aips.md
      - Components: user-manual/components.md
      - Glossary: user-manual/glossary.md
  - Administrator manual: admin-manual/
  - Developer manual: dev-manual/
  - About:
      - Repository: https://github.com/artefactual-sdps/enduro
      - Issues: https://github.com/artefactual-sdps/enduro/issues
      - License: https://github.com/artefactual-sdps/enduro/blob/main/LICENSE

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - autorefs
  - literate-nav:
      nav_file: README.md
  - search
  - swagger-ui-tag

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
  highlightjs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
