package auth

const (
	IngestSIPSDownloadAttr         = "ingest:sips:download"
	IngestSIPSListAttr             = "ingest:sips:list"
	IngestSIPSReadAttr             = "ingest:sips:read"
	IngestSIPSReviewAttr           = "ingest:sips:review"
	IngestSIPSUploadAttr           = "ingest:sips:upload"
	IngestSIPSWorkflowsListAttr    = "ingest:sips:workflows:list"
	IngestUsersListAttr            = "ingest:users:list"
	StorageAIPSCreateAttr          = "storage:aips:create"
	StorageAIPSDeletionRequestAttr = "storage:aips:deletion:request"
	StorageAIPSDeletionReviewAttr  = "storage:aips:deletion:review"
	StorageAIPSDownloadAttr        = "storage:aips:download"
	StorageAIPSListAttr            = "storage:aips:list"
	StorageAIPSMoveAttr            = "storage:aips:move"
	StorageAIPSReadAttr            = "storage:aips:read"
	StorageAIPSReviewAttr          = "storage:aips:review"
	StorageAIPSSubmitAttr          = "storage:aips:submit"
	StorageAIPSWorkflowsListAttr   = "storage:aips:workflows:list"
	StorageLocationsAIPSListAttr   = "storage:locations:aips:list"
	StorageLocationsCreateAttr     = "storage:locations:create"
	StorageLocationsListAttr       = "storage:locations:list"
	StorageLocationsReadAttr       = "storage:locations:read"
)
