on: [workflow_dispatch]
name: Pulumi
jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: hack/pulumi/go.mod
      - name: Download Go dependencies
        run: go mod download
        working-directory: hack/pulumi
      - name: Refresh and update Pulumi stack
        uses: pulumi/actions@8e5e406f4007fca908480587cb9893c07090f58d # v7.0.0
        with:
          command: up
          refresh: true
          stack-name: dev
          work-dir: hack/pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
          DOCKER_BUILDKIT: 1
      - name: Configure kubectl
        uses: azure/k8s-set-context@89b837d75b40a7bd2ddafde837473c212db8b313 # v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.DO_DEV_KUBECONFIG }}
      - name: Flush existing data
        run: |
          kubectl config set-context --current --namespace sdps
          kubectl delete job --all
          kubectl create -f hack/kube/tools/mysql-recreate-databases-job.yaml
          kubectl create -f hack/kube/tools/minio-recreate-buckets-job.yaml
          kubectl wait --for=condition=complete --timeout=120s job --all
          kubectl rollout restart deployment temporal
          kubectl rollout restart deployment enduro
          kubectl rollout restart statefulset enduro-a3m
          kubectl create -f hack/kube/base/mysql-create-locations-job.yaml
