on:
  pull_request:
  push:
    branches:
      - main
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: Check mod tidy
        run: make mod-tidy-check
      - name: Test
        run: make test-ci
      - name: Determine skip-codecov
        uses: ./.github/actions/skip-codecov
        id: skip-codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        if: ${{ steps.skip-codecov.outputs.skip != 'true' }}
        with:
          files: covreport
          flags: backend
          name: backend
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
